"""CLI: validate an .adef.toml definition and write the selected outputs (C header, C++
wrapper, LuaJIT base module, C++ implementation stub) into the generated directory, or
(gendeps mode) print a Makefile fragment naming those outputs for one definition.
"""

import argparse
import sys
from pathlib import Path

from api_gen import emit_binding_cpp as hpp
from api_gen import emit_binding_lua as lua
from api_gen import emit_c as h
from api_gen import emit_stub_cpp as stub_cpp
from api_gen import model
from api_gen.emitter import Emitter

SUFFIX = ".adef.toml"
GENDEPS_BANNER = "# GENERATED by api_gen gendeps; do not edit."
# Keyed by output token, in the order objections are reported and outputs written.
EMITTERS: dict[str, Emitter] = {"h": h, "hpp": hpp, "lua": lua, "stub_cpp": stub_cpp}


def output_paths(*, stem: str, exercise: str) -> dict[str, Path]:
    """Every output token and its path for a definition's stem and exercise, relative to
    --generated. The one place that knows the tokens and the layout; `--outputs`, the
    generation mode and gendeps all read it.
    """
    return {
        "h": Path("include") / exercise / f"{stem}.h",
        "hpp": Path("include") / exercise / f"{stem}.hpp",
        "lua": Path("binding") / f"{stem}.lua",
        "stub_cpp": Path("stub") / f"{stem}.cpp",
    }


TOKENS = tuple(output_paths(stem="", exercise=""))


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if argv[:1] == ["gendeps"]:
        return _gendeps_main(argv[1:])
    return _generate_main(argv)


def _outputs(text: str) -> tuple[str, ...]:
    """`--outputs`: comma-separated tokens, each known and none repeated, returned in
    `TOKENS` order."""
    tokens = text.split(",")
    valid = ", ".join(TOKENS)
    for i, token in enumerate(tokens):
        if token not in TOKENS:
            raise argparse.ArgumentTypeError(f"unknown output '{token}' (valid: {valid})")
        if token in tokens[:i]:
            raise argparse.ArgumentTypeError(f"output '{token}' repeated (valid: {valid})")
    return tuple(t for t in TOKENS if t in tokens)


def _library(text: str) -> str:
    """`--library`: a file name; an empty one names nothing to load."""
    if not text:
        raise argparse.ArgumentTypeError("must name a file")
    return text


def _add_outputs_argument(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--outputs", type=_outputs, default=TOKENS,
        help=f"comma-separated outputs to produce, from {','.join(TOKENS)} (default: all)",
    )


def _objections(api: model.Api, outputs: tuple[str, ...]) -> list[str]:
    """Every selected emitter's objection to `api`, one line per distinct message:
    objections from different emitters that share the same text after their own
    `<emitter>: ` prefix are reported once, under every emitter that raised it,
    comma-joined in `EMITTERS` order."""
    labels_by_message: dict[str, list[str]] = {}
    for token in outputs:
        emitter = EMITTERS[token]
        for p in emitter.validate(api):
            message = p.removeprefix(f"{emitter.LABEL}: ")
            labels_by_message.setdefault(message, []).append(emitter.LABEL)
    return [f"{', '.join(labels)}: {message}" for message, labels in labels_by_message.items()]


def _generate_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="generate userspace API artifacts from an API definition"
    )
    parser.add_argument("definition", type=Path, help="path to a *.adef.toml file")
    parser.add_argument("--generated", type=Path, required=True, help="output directory")
    parser.add_argument(
        "--exercise", required=True, help="exercise directory name, for the include subdirectory"
    )
    parser.add_argument(
        "--library",
        type=_library,
        help="shared library file name the Lua module loads (default: _general._library)",
    )
    _add_outputs_argument(parser)
    args = parser.parse_args(argv)
    outputs: tuple[str, ...] = args.outputs

    definition: Path = args.definition
    if not definition.name.endswith(SUFFIX):
        print(f"api_gen: {definition}: file name must end in {SUFFIX}", file=sys.stderr)
        return 2

    stem = definition.name[: -len(SUFFIX)]
    source = definition.name
    try:
        api = model.load(definition)
        if args.library is not None:
            model.check_literal_text(args.library, "--library")
    except model.DefinitionError as e:
        print(f"api_gen: {definition}: {e}", file=sys.stderr)
        return 2
    library = args.library if args.library is not None else api.library
    problems = _objections(api, outputs)
    if "lua" in outputs and library is None:
        problems.append(f"{lua.LABEL}: no library to load: pass --library or set _general._library")
    if problems:
        for problem in problems:
            print(f"api_gen: {definition}: {problem}", file=sys.stderr)
        return 2

    paths = output_paths(stem=stem, exercise=args.exercise)
    texts = {
        paths[token]: EMITTERS[token].emit(api, source_name=source, stem=stem, library=library) for token in outputs
    }

    generated: Path = args.generated
    for relpath, text in texts.items():
        out_path = generated / relpath
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")

    written = " ".join(str(relpath) for relpath in texts)
    print(f"api_gen: {stem}: wrote {written} under {generated}", file=sys.stderr)
    return 0


def _gendeps_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="api_gen gendeps",
        description="print a Makefile fragment naming the outputs for a definition",
    )
    parser.add_argument("definitions", nargs="*", help="path to a *.adef.toml file")
    _add_outputs_argument(parser)
    args = parser.parse_args(argv)

    if len(args.definitions) != 1:
        print("api_gen: gendeps takes exactly one definition", file=sys.stderr)
        return 2

    definition = args.definitions[0]
    name = Path(definition).name
    if not name.endswith(SUFFIX):
        print(f"api_gen: {definition}: file name must end in {SUFFIX}", file=sys.stderr)
        return 2
    stem = name[: -len(SUFFIX)]

    block = _gendeps_block(definition=definition, stem=stem, outputs=args.outputs)
    sys.stdout.write(GENDEPS_BANNER + "\n" + block)
    return 0


def _gendeps_block(*, definition: str, stem: str, outputs: tuple[str, ...]) -> str:
    paths = output_paths(stem=stem, exercise="$(BASE)")
    targets = " \\\n".join(f"  $(GEN)/{paths[token]}" for token in outputs)
    recipe = (
        "PYTHONPATH=$(API_GEN) PYTHONDONTWRITEBYTECODE=1 "
        f"python3 -m api_gen $< --generated $(GEN) --exercise $(BASE) --outputs={','.join(outputs)}"
    )
    return f"GENERATED := \\\n{targets}\n\n$(GENERATED) &: {definition}\n\t{recipe}\n"


if __name__ == "__main__":
    sys.exit(main())
