"""CLI: validate an .adef.toml definition and write the selected outputs (see `EMITTERS`)
into the generated directory, or (gendeps mode) print a Makefile fragment naming those
outputs for one definition. The definition's `_general._name` names every output.
"""

import argparse
import sys
from collections.abc import Iterable
from pathlib import Path

from api_gen import model, naming
from api_gen.emitters import EMITTERS
from api_gen.emitters.emitter import ToolError

SUFFIX = ".adef.toml"
GENDEPS_BANNER = "# GENERATED by api_gen gendeps; do not edit."
TOKENS = tuple(EMITTERS)


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if argv[:1] == ["gendeps"]:
        return _gendeps_main(argv[1:])
    return _generate_main(argv)


def _outputs(text: str) -> tuple[str, ...]:
    """`--outputs`: comma-separated tokens, each known and none repeated, returned in
    `TOKENS` order."""
    tokens = text.split(",")
    valid = ", ".join(TOKENS)
    for i, token in enumerate(tokens):
        if token not in TOKENS:
            raise argparse.ArgumentTypeError(f"unknown output '{token}' (valid: {valid})")
        if token in tokens[:i]:
            raise argparse.ArgumentTypeError(f"output '{token}' repeated (valid: {valid})")
    return tuple(t for t in TOKENS if t in tokens)


def _add_outputs_argument(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--outputs", type=_outputs, default=TOKENS,
        help=f"comma-separated outputs to produce, from {','.join(TOKENS)} (default: all)",
    )


def _flag_objections(flag: str, value: str | None, *, names: str) -> list[str]:
    """The objections to a flag the outputs spell inside a string literal: held to
    `_general._bound_library`'s rule, and not empty, since an empty one names no `names`."""
    if value is None:
        return []
    if not value:
        return [f"{flag} must name a {names}"]
    try:
        model.check_literal_text(value, flag)
    except model.DefinitionError as e:
        return [str(e)]
    return []


def _objections(api: model.Api, outputs: tuple[str, ...]) -> list[str]:
    """Every selected emitter's objection to `api`, one line per distinct message:
    objections from different emitters that share the same text after their own
    `<emitter>: ` prefix are reported once, under every emitter that raised it,
    comma-joined in `EMITTERS` order."""
    labels_by_message: dict[str, list[str]] = {}
    for token in outputs:
        emitter = EMITTERS[token]
        for objection in emitter.validate(api):
            message = objection.removeprefix(f"{emitter.LABEL}: ")
            labels_by_message.setdefault(message, []).append(emitter.LABEL)
    return [f"{', '.join(labels)}: {message}" for message, labels in labels_by_message.items()]


def _linkage_objections(outputs: tuple[str, ...], library: str | None) -> list[str]:
    """The objections to `library`, the resolved one the Lua module loads and the Rust
    binding links, which need the flag as well as the definition."""
    objections = []
    loaders = [EMITTERS[token].LABEL for token in ("lua", "rs") if token in outputs]
    if loaders and library is None:
        objections.append(f"{', '.join(loaders)}: no library named; set _general._bound_library or --library")
    if "rs" in outputs and library is not None and naming.rust_link_name(library) is None:
        objections.append(
            f"{EMITTERS['rs'].LABEL}: library '{library}' is not of the form lib<name>.so, the one a Rust binding links"
        )
    return objections


def _report(definition: Path | str, objections: Iterable[object]) -> int:
    """Print each objection to `definition` on stderr; the exit code for them, 2."""
    for objection in objections:
        print(f"api_gen: {definition}: {objection}", file=sys.stderr)
    return 2


def _generate_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="generate userspace API artifacts from an API definition"
    )
    parser.add_argument("definition", type=Path, help="path to a *.adef.toml file")
    parser.add_argument("--generated", type=Path, required=True, help="output directory")
    parser.add_argument(
        "--project", required=True,
        help="project name, its directory's: the include subdirectory and the base of each _wrapped_api._headers path",
    )
    parser.add_argument(
        "--library",
        help="shared library file name the Lua module loads and the Rust binding links (default: _general._bound_library)",
    )
    _add_outputs_argument(parser)
    args = parser.parse_args(argv)
    outputs: tuple[str, ...] = args.outputs

    definition: Path = args.definition
    if not definition.name.endswith(SUFFIX):
        print(f"api_gen: {definition}: file name must end in {SUFFIX}", file=sys.stderr)
        return 2

    source = definition.name
    project: str = args.project
    flag = _flag_objections("--project", project, names="directory")
    flag += _flag_objections("--library", args.library, names="file")
    try:
        api = model.load(definition)
    except model.DefinitionError as e:
        objections = [str(o) for o in e.objections()]
    else:
        library = args.library if args.library is not None else api.library
        objections = _objections(api, outputs) + ([] if flag else _linkage_objections(outputs, library))
    objections += flag
    if objections:
        return _report(definition, objections)

    texts: dict[Path, str] = {}
    try:
        for token in outputs:
            emitter = EMITTERS[token]
            texts[emitter.output_path(name=api.name, project=project)] = emitter.emit(
                api, source_name=source, name=api.name, library=library, project=project
            )
    except ToolError as e:
        print(f"api_gen: {e}", file=sys.stderr)
        return 2

    generated: Path = args.generated
    for relpath, text in texts.items():
        out_path = generated / relpath
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")

    written = " ".join(str(relpath) for relpath in texts)
    print(f"api_gen: {api.name}: wrote {written} under {generated}", file=sys.stderr)
    return 0


def _gendeps_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="api_gen gendeps",
        description="print a Makefile fragment naming the outputs for a definition",
    )
    parser.add_argument("definitions", nargs="*", help="path to a *.adef.toml file")
    _add_outputs_argument(parser)
    args = parser.parse_args(argv)

    if len(args.definitions) != 1:
        print("api_gen: gendeps takes exactly one definition", file=sys.stderr)
        return 2

    definition = args.definitions[0]
    if not definition.endswith(SUFFIX):
        print(f"api_gen: {definition}: file name must end in {SUFFIX}", file=sys.stderr)
        return 2
    try:
        api = model.load(Path(definition))
    except model.DefinitionError as e:
        return _report(definition, e.objections())

    block = _gendeps_block(definition=definition, name=api.name, outputs=args.outputs)
    sys.stdout.write(GENDEPS_BANNER + "\n" + block)
    return 0


def _gendeps_block(*, definition: str, name: str, outputs: tuple[str, ...]) -> str:
    """The make fragment for `definition`'s selected outputs, the generator's only make-specific
    text: another build system (ninja, gradle, ...) is another renderer of the same three inputs,
    chosen by a `gendeps` flag, and nothing above this function changes."""
    paths = (EMITTERS[token].output_path(name=name, project="$(BASE)") for token in outputs)
    targets = " \\\n".join(f"  $(GEN)/{path}" for path in paths)
    recipe = (
        "PYTHONPATH=$(API_GEN) PYTHONDONTWRITEBYTECODE=1 "
        f"python3 -m api_gen $< --generated $(GEN) --project $(BASE) --outputs={','.join(outputs)}"
    )
    return f"GENERATED := \\\n{targets}\n\n$(GENERATED) &: {definition}\n\t{recipe}\n"


if __name__ == "__main__":
    sys.exit(main())
