"""CLI: validate an .adef.toml definition and write its C header and
LuaJIT base module into the generated directory, or (gendeps mode) print a
Makefile fragment naming those outputs for a set of definitions.
"""

import argparse
import sys
from pathlib import Path

from api_gen import emit_c, emit_lua, model

SUFFIX = ".adef.toml"
GENDEPS_BANNER = "# GENERATED by api_gen gendeps; do not edit."


def output_paths(*, stem: str, exercise: str) -> tuple[Path, Path]:
    """Return the (header, lua) output paths for a definition's stem and
    exercise, relative to --generated. The one place that knows the layout;
    both the generation mode and gendeps call it.
    """
    return Path("include") / exercise / f"{stem}.h", Path("binding") / f"{stem}.lua"


def main() -> int:
    argv = sys.argv[1:]
    if argv[:1] == ["gendeps"]:
        return _gendeps_main(argv[1:])
    return _generate_main(argv)


def _generate_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="generate userspace API artifacts from an API definition"
    )
    parser.add_argument("definition", type=Path, help="path to a *.adef.toml file")
    parser.add_argument("--generated", type=Path, required=True, help="output directory")
    parser.add_argument(
        "--exercise", required=True, help="exercise directory name, for the include subdirectory"
    )
    parser.add_argument(
        "--library",
        help="shared library file name the Lua module loads (default: general.library)",
    )
    args = parser.parse_args(argv)

    definition: Path = args.definition
    if not definition.name.endswith(SUFFIX):
        print(f"api_gen: {definition}: file name must end in {SUFFIX}", file=sys.stderr)
        return 2

    stem = definition.name[: -len(SUFFIX)]
    source = definition.name
    try:
        api = model.load(definition)
        library = args.library or api.library
        if library is None:
            raise model.DefinitionError(
                "no library for the Lua module: pass --library or set general.library"
            )
        header_path, lua_path = output_paths(stem=stem, exercise=args.exercise)
        outputs = {
            header_path: emit_c.header(api, source_name=source),
            lua_path: emit_lua.module(api, source_name=source, library=library),
        }
    except model.DefinitionError as e:
        print(f"api_gen: {definition}: {e}", file=sys.stderr)
        return 2

    generated: Path = args.generated
    reported = []
    for relpath, text in outputs.items():
        out_path = generated / relpath
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")
        reported.append(str(relpath))

    paths = " ".join(reported)
    print(f"api_gen: {stem}: wrote {paths} under {generated}", file=sys.stderr)
    return 0


def _gendeps_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="api_gen gendeps",
        description="print a Makefile fragment naming the outputs for each definition",
    )
    parser.add_argument("--generated", required=True, help="output directory, printed as given")
    parser.add_argument("--exercise", required=True, help="exercise directory name, printed as given")
    parser.add_argument("definitions", nargs="*", help="paths to *.adef.toml files")
    args = parser.parse_args(argv)

    blocks = []
    for definition in args.definitions:
        name = Path(definition).name
        if not name.endswith(SUFFIX):
            print(f"api_gen: {definition}: file name must end in {SUFFIX}", file=sys.stderr)
            return 2
        stem = name[: -len(SUFFIX)]
        blocks.append(
            _gendeps_block(
                definition=definition, directory=args.generated, exercise=args.exercise, stem=stem
            )
        )

    sys.stdout.write(GENDEPS_BANNER + "\n" + "".join(blocks))
    return 0


def _gendeps_block(*, definition: str, directory: str, exercise: str, stem: str) -> str:
    header, lua = output_paths(stem=stem, exercise=exercise)
    targets = f"{directory}/{header} {directory}/{lua}"
    recipe = (
        f"PYTHONPATH=$(API_GEN) PYTHONDONTWRITEBYTECODE=1 "
        f"python3 -m api_gen $< --generated {directory} --exercise {exercise}"
    )
    return (
        f"GENERATED += {targets}\n"
        f"{targets} &: {definition}\n"
        f"\t{recipe}\n"
        f"\n"
    )


if __name__ == "__main__":
    sys.exit(main())
