"""The C header, and the declaration text the Lua module hands to ffi.cdef."""

from api_gen import naming
from api_gen.model import Api, BitConstGroup, Function, OpaqueRef, Param, Struct, TypedConst


def c_type(api: Api, type_name: str) -> str:
    """C spelling of a definition type used by value."""
    if type_name in naming.BUILTIN_C_TYPES:
        return naming.BUILTIN_C_TYPES[type_name]
    return naming.type_name(api.namespace, type_name)


def int_literal(value: int, fmt: str) -> str:
    """An integer spelled for C and Lua alike: decimal, or lower-case unpadded hex."""
    if fmt == "hex":
        return f"-0x{-value:x}" if value < 0 else f"0x{value:x}"
    return str(value)


def _term_text(ns: str, term: str) -> str:
    """A composed entry's list term as the header spells it: a literal exactly as the
    definition wrote it, a name as its constant."""
    try:
        int(term, 0)
    except ValueError:
        return naming.const_name(ns, term)
    return term


def c_params(api: Api, param: Param) -> list[tuple[str, str]]:
    """(C type, name) of each C parameter a definition parameter becomes: a `memory`
    parameter is the pointer and its byte count, every other parameter itself."""
    params = [(param_type(api, param), param.name)]
    if param.count_type is not None:
        params.append((naming.BUILTIN_C_TYPES[param.count_type], naming.count_param(param.name)))
    return params


def param_type(api: Api, param: Param) -> str:
    if param.type == "memory":
        return "const void*" if param.ref == "in" else "void*"
    base = c_type(api, param.type)
    if param.ref == "in":
        return f"const {base}*"
    if param.ref is not None:
        return f"{base}*"
    return base


def header(api: Api, *, source_name: str) -> str:
    ns = api.namespace
    c_api, api_macro, impl = naming.c_api_macro(ns), naming.api_macro(ns), naming.impl_macro(ns)
    prelude = f"""\
/* GENERATED by vdev/api_gen from {source_name}; do not edit. */
#pragma once

#include <stdint.h>

#if defined(__cplusplus)
# define {c_api} extern "C"
#else
# define {c_api}
#endif

#if defined({impl})
# define {api_macro} {c_api} __attribute__((visibility("default")))
#else
# define {api_macro} {c_api}
#endif

"""
    text = prelude + declarations(api, function_prefix=f"{api_macro} ")
    if api.driver_data is not None:
        asserts = "".join(
            f'static_assert({naming.const_name(ns, key)} == {macro}, '
            f'"{naming.const_name(ns, key)} must match {macro}");\n'
            for key, macro in api.driver_data.const_pins
        )
        text += f"""\

#if defined({impl})
# include "{api.driver_data.header}"
/* ABI pins: the implementation build fails if a relayed constant disagrees with the driver's UAPI header */
# include <assert.h>
{asserts}#endif
"""
    return text


def cdef(api: Api) -> str:
    """The declaration text the Lua module hands to ffi.cdef: a typedef of its base type
    for each typed enum (not its body, since the Lua module carries constants as literals),
    opaque and struct declarations, and function declarations with no visibility macro.
    """
    typedefs = [
        f"typedef {naming.BASE_C_TYPES[t.base_type]} {naming.type_name(api.namespace, t.name)};\n"
        for t in api.typed_consts
    ]
    return "\n".join(typedefs + [declarations(api, function_prefix="", constants=False)])


def declarations(api: Api, *, function_prefix: str, constants: bool = True) -> str:
    ns = api.namespace
    blocks = []
    if constants:
        blocks.append(_version_enum(api))
        blocks += [_comment_line(g.docstring) + _bit_enum(api, g) for g in api.bit_const_groups]
        blocks += [
            _comment_line(g.docstring)
            + _anonymous_enum(
                [
                    (
                        naming.const_name(ns, c.key),
                        " + ".join(_term_text(ns, p) for p in c.parts) if c.parts else int_literal(c.value, c.format),
                        c.docstring,
                    )
                    for c in g.entries
                ]
            )
            for g in api.const_groups
        ]
        blocks += [_typed_enum(api, t) for t in api.typed_consts]
        blocks += [
            _comment_line(g.docstring)
            + "".join(
                f'static const char {naming.const_name(ns, c.key)}[] = "{c.value}";{_trailing(c.docstring)}\n'
                for c in g.entries
            )
            for g in api.string_const_groups
        ]
    blocks += [_opaque(api, o) for o in api.opaque_refs]
    blocks += [_struct(api, s) for s in api.structs]
    if api.functions:
        blocks.append("".join(_function(api, f, function_prefix) for f in api.functions))
    return "\n".join(blocks)


def _comment_line(doc: str | None) -> str:
    return f"/* {doc} */\n" if doc else ""


def _trailing(doc: str | None) -> str:
    return f" /* {doc} */" if doc else ""


def _anonymous_enum(entries: list[tuple[str, str, str | None]]) -> str:
    """`enum { ... };` from (name, value text, docstring) entries."""
    lines = "".join(
        f"  {name} = {value}{',' if i < len(entries) - 1 else ''}{_trailing(doc)}\n"
        for i, (name, value, doc) in enumerate(entries)
    )
    return "enum {\n" + lines + "};\n"


def _version_enum(api: Api) -> str:
    shifts = (24, 16, 8, 0)
    value = " | ".join(f"(0x{b:02x} << {s})" for b, s in zip(api.version, shifts))
    return _anonymous_enum([(naming.version_const(api.namespace), value, None)])


def _bit_enum(api: Api, group: BitConstGroup) -> str:
    ns = api.namespace
    return _anonymous_enum(
        [
            (
                naming.const_name(ns, c.key),
                f"(1u << {c.bit})" if c.bit is not None else " | ".join(_term_text(ns, p) for p in c.parts),
                c.docstring,
            )
            for c in group.entries
        ]
    )


def _typed_enum(api: Api, typed: TypedConst) -> str:
    ns = api.namespace
    name = naming.type_name(ns, typed.name)
    entries = typed.entries
    lines = "".join(
        f"  {naming.const_name(ns, e.key)} = {int_literal(e.value, e.format)}"
        f"{',' if i < len(entries) - 1 else ''}{_trailing(e.docstring)}\n"
        for i, e in enumerate(entries)
    )
    return f"{_comment_line(typed.docstring)}enum {name} {{\n{lines}}};\ntypedef enum {name} {name};\n"


def _opaque(api: Api, opaque: OpaqueRef) -> str:
    ns = api.namespace
    target = naming.opaque_struct(ns, opaque.name)
    return (
        f"{_comment_line(opaque.docstring)}struct {target};\n"
        f"typedef struct {target}* {naming.type_name(ns, opaque.name)};\n"
    )


def _struct(api: Api, struct: Struct) -> str:
    name = naming.type_name(api.namespace, struct.name)
    decls = [f"{c_type(api, f.type)} {f.name};" for f in struct.fields]
    width = max(len(d) for d in decls)
    lines = "".join(
        f"\t{d.ljust(width)} /* {f.docstring} */\n" if f.docstring else f"\t{d}\n"
        for d, f in zip(decls, struct.fields)
    )
    return f"{_comment_line(struct.docstring)}struct {name} {{\n{lines}}};\ntypedef struct {name} {name};\n"


def _function(api: Api, fn: Function, prefix: str) -> str:
    params = ", ".join(f"{t} {n}" for p in fn.params for t, n in c_params(api, p)) or "void"
    returns = c_type(api, fn.returns)
    name = naming.function_name(api.namespace, fn.name)
    return f"{_comment_line(' '.join(fn.docs()))}{prefix}{returns} {name}({params});\n"
