"""The C header, and the declaration text the Lua module hands to ffi.cdef."""

from api_gen import naming
from api_gen.model import Api, Function, OpaqueRef, Param, Struct, TypedConst


def c_type(api: Api, type_name: str) -> str:
    """C spelling of a definition type used by value."""
    if type_name in naming.BUILTIN_C_TYPES:
        return naming.BUILTIN_C_TYPES[type_name]
    return naming.type_name(api.namespace, type_name)


def param_type(api: Api, param: Param) -> str:
    if param.type == "memory":
        return "const void*" if param.inref else "void*"
    base = c_type(api, param.type)
    if param.outref:
        return f"{base}*"
    if param.inref:
        return f"const {base}*"
    return base


def header(api: Api, *, source_name: str) -> str:
    ns = api.namespace
    c_api, api_macro, impl = naming.c_api_macro(ns), naming.api_macro(ns), naming.impl_macro(ns)
    prelude = f"""\
/* GENERATED by vdev/api_gen from {source_name}; do not edit. Kept LuaJIT-FFI friendly: nothing in macros is needed across the barrier. */
#pragma once

#include <stdint.h>

#if defined(__cplusplus)
# define {c_api} extern "C"
#else
# define {c_api}
#endif

#if defined({impl})
# define {api_macro} {c_api} __attribute__((visibility("default")))
#else
# define {api_macro} {c_api}
#endif

"""
    return prelude + declarations(api, function_prefix=f"{api_macro} ")


def cdef(api: Api) -> str:
    """The header's declarations with no preprocessor lines and no visibility macro."""
    return declarations(api, function_prefix="")


def declarations(api: Api, *, function_prefix: str) -> str:
    blocks = [_version_enum(api)]
    if api.bit_consts:
        blocks.append(_bit_enum(api))
    blocks += [_typed_enum(api, t) for t in api.typed_consts]
    blocks += [_opaque(api, o) for o in api.opaque_refs]
    blocks += [_struct(api, s) for s in api.structs]
    if api.functions:
        blocks.append("".join(_function(api, f, function_prefix) for f in api.functions))
    return "\n".join(blocks)


def _comment_line(doc: str | None) -> str:
    return f"/* {doc} */\n" if doc else ""


def _trailing(doc: str | None) -> str:
    return f" /* {doc} */" if doc else ""


def _version_enum(api: Api) -> str:
    shifts = (24, 16, 8, 0)
    value = " | ".join(f"(0x{b:02x} << {s})" for b, s in zip(api.version, shifts))
    return f"enum {{\n  {naming.version_const(api.namespace)} = {value}\n}};\n"


def _bit_enum(api: Api) -> str:
    ns = api.namespace
    lines = []
    for i, c in enumerate(api.bit_consts):
        if c.bit is not None:
            value = f"(1u << {c.bit})"
        else:
            value = " | ".join(naming.const_name(ns, p) for p in c.parts)
        comma = "," if i < len(api.bit_consts) - 1 else ""
        lines.append(f"  {naming.const_name(ns, c.key)} = {value}{comma}{_trailing(c.docstring)}\n")
    return "enum {\n" + "".join(lines) + "};\n"


def _typed_enum(api: Api, typed: TypedConst) -> str:
    ns = api.namespace
    name = naming.type_name(ns, typed.name)
    lines = "".join(
        f"  {naming.const_name(ns, e.key)} = {e.value},{_trailing(e.docstring)}\n" for e in typed.entries
    )
    return f"{_comment_line(typed.docstring)}enum {name} {{\n{lines}}};\ntypedef enum {name} {name};\n"


def _opaque(api: Api, opaque: OpaqueRef) -> str:
    ns = api.namespace
    target = naming.opaque_struct(ns, opaque.name)
    return (
        f"{_comment_line(opaque.docstring)}struct {target};\n"
        f"typedef struct {target}* {naming.type_name(ns, opaque.name)};\n"
    )


def _struct(api: Api, struct: Struct) -> str:
    name = naming.type_name(api.namespace, struct.name)
    decls = [f"{c_type(api, f.type)} {f.name};" for f in struct.fields]
    width = max(len(d) for d in decls)
    lines = "".join(
        f"\t{d.ljust(width)} /* {f.docstring} */\n" if f.docstring else f"\t{d}\n"
        for d, f in zip(decls, struct.fields)
    )
    return f"{_comment_line(struct.docstring)}struct {name} {{\n{lines}}};\ntypedef struct {name} {name};\n"


def _function(api: Api, fn: Function, prefix: str) -> str:
    docs = [fn.docstring] if fn.docstring else []
    docs += [f"{p.name}: {p.docstring}" for p in fn.params if p.docstring]
    params = ", ".join(f"{param_type(api, p)} {p.name}" for p in fn.params) or "void"
    returns = c_type(api, fn.returns)
    name = naming.function_name(api.namespace, fn.name)
    return f"{_comment_line(' '.join(docs))}{prefix}{returns} {name}({params});\n"
