"""A C++ implementation stub: every function defined, every body `return {};` to be replaced."""

from api_gen import emit_c, naming
from api_gen.emit_binding_cpp import cpp_keyword_objections
from api_gen.model import Api, Function

LABEL = "stub"


def validate(api: Api) -> list[str]:
    """Every objection the stub has to `api`: a name that is a C++ keyword."""
    return [f"{LABEL}: {p}" for p in cpp_keyword_objections(api)]


def emit(api: Api, *, source_name: str, stem: str, library: str | None) -> str:
    """The implementation stub."""
    impl = naming.impl_macro(api.namespace)
    prelude = f"""\
// GENERATED by vdev/api_gen from {source_name}: implementation stub. Copy into lib/ once and replace every body; the generator never touches lib/.
#define {impl}
#include "{stem}.h"
#undef {impl}

#include <cerrno>
#include <cstdint>
#include <cstring>
"""
    return prelude + "".join("\n" + _definition(api, f) for f in api.functions)


def _definition(api: Api, fn: Function) -> str:
    ns = api.namespace
    voids = "".join(f"  (void){n};\n" for p in fn.params for _, n in emit_c.c_params(api, p))
    return (
        f"{naming.api_macro(ns)} {emit_c.c_type(api, fn.returns)} {naming.function_name(ns, fn.name)}"
        f"({emit_c.param_list(api, fn)}) {{\n"
        f"{voids}"
        "  // replace: not implemented\n"
        "  return {};\n"
        "}\n"
    )
