"""The LuaJIT base module: ffi.cdef of the header, constants, raw functions and a class
per opaque ref that names a constructor."""

from api_gen import emit_c, naming
from api_gen.model import Api, DefinitionError, Function, OpaqueRef, Param


def module(api: Api, *, source_name: str, library: str) -> str:
    ns = api.namespace
    out = [
        f"-- GENERATED by vdev/api_gen from {source_name}; do not edit.\n",
        'local ffi = require("ffi")\n\n',
        _cdef(emit_c.cdef(api)),
        f'\nlocal lib = ffi.load("{library}")\n\nlocal M = {{}}\n\n',
    ]

    sections = _constant_sections(api)
    classes = {naming.upper_camel(o.class_name) for o in api.opaque_refs if o.ctor is not None}
    clash = next((name for _, literals in sections for name, _ in literals if name in classes), None)
    if clash is not None:
        raise DefinitionError(f"Lua module: M.{clash} would be both a constant and a class")
    for doc, literals in sections:
        out += [f"-- {line}\n" for line in (doc or "").splitlines()]
        out += [f"M.{name} = {value}\n" for name, value in literals]

    for typed in api.typed_consts:
        names = "".join(
            f'    [M.{c}] = "{c}",\n' for c in (naming.lua_const_name(e.key) for e in typed.entries)
        )
        out.append(
            f"\nlocal {typed.name}_names = {{\n{names}}}\n"
            f"function M.{typed.name}_to_str(value)\n    return {typed.name}_names[value]\nend\n"
        )
    returns = {f.returns for f in api.functions}
    if len(returns) == 1:
        out.append(f"M.error_to_str = M.{returns.pop()}_to_str\n")

    raw = "".join(f"    {f.name} = lib.{naming.function_name(ns, f.name)},\n" for f in api.functions)
    out.append(f"\nM.raw = {{\n{raw}}}\n")

    out += [_class(api, o) for o in api.opaque_refs if o.ctor is not None]

    out.append("\nreturn M\n")
    return "".join(out)


def _version_literal(api: Api) -> str:
    return f"0x{api.version_value():08x}"


def _constant_sections(api: Api) -> list[tuple[str | None, list[tuple[str, str]]]]:
    """Every constant's (name, Lua literal), in the same order the C header defines them,
    as (docstring, literals) sections: one per constant group, the rest undocumented.
    Every value is the model's already-resolved one; a composed entry's sum was computed,
    and a bit group's overlap-checked, once in model.py."""
    name = naming.lua_const_name
    sections = [(None, [(name(naming.VERSION_KEY), _version_literal(api))])]
    sections += [
        (g.docstring, [(name(c.key), emit_c.int_literal(c.value, c.format)) for c in g.entries])
        for g in api.bit_const_groups
    ]
    sections += [
        (g.docstring, [(name(c.key), emit_c.int_literal(c.value, c.format)) for c in g.entries])
        for g in api.const_groups
    ]
    rest = [(name(e.key), emit_c.int_literal(e.value, e.format)) for t in api.typed_consts for e in t.entries]
    sections.append((None, rest))
    sections += [
        (g.docstring, [(name(c.key), f'"{c.value}"') for c in g.entries])
        for g in api.string_const_groups
    ]
    return sections


def _cdef(text: str) -> str:
    return f"ffi.cdef[[\n{text}]]\n"


def _doc_lines(fn: Function) -> str:
    return "".join(f"-- {line}\n" for doc in fn.docs() for line in doc.splitlines())


def _ok_const(api: Api, fn: Function) -> str:
    typed = next(t for t in api.typed_consts if t.name == fn.returns)
    ok = next(e for e in typed.entries if e.value == 0)
    return naming.lua_const_name(ok.key)


def _is_opaque_value(param: Param, opaque: str) -> bool:
    return param.type == opaque and param.ref is None


def _lua_value(api: Api, type_name: str, expr: str, *, indent: str = "    ") -> str:
    """u32 and enum values become Lua numbers, a struct a table of its fields converted
    the same way (nested structs included); u64 and opaque values stay cdata. `indent`
    is the indentation of the line the expression starts on."""
    kind = api.kind(type_name)
    if kind == "struct":
        fields = next(s for s in api.structs if s.name == type_name).fields
        inner = indent + "    "
        body = "".join(
            f"{inner}{f.name} = {_lua_value(api, f.type, f'{expr}.{f.name}', indent=inner)},\n" for f in fields
        )
        return f"{{\n{body}{indent}}}"
    return f"tonumber({expr})" if type_name == "u32" or kind == "enum" else expr


def _box(api: Api, type_name: str) -> str:
    """The ffi.new type for a value the C side reaches through a pointer: a struct
    itself, anything else a one-element array."""
    c_type = emit_c.c_type(api, type_name)
    return c_type if api.kind(type_name) == "struct" else f"{c_type}[1]"


def _alloc(api: Api, p: Param) -> str:
    """The cdata a non-memory reference parameter's C pointer reaches: an `in` or `inout`
    value arrives as a Lua value (a table or cdata for a struct) and is copied in; an
    `out` value starts zeroed."""
    init = "" if p.ref == "out" else f", {p.name}"
    return f'    local {p.name} = ffi.new("{_box(api, p.type)}"{init})\n'


def _read_back(api: Api, p: Param) -> str:
    """The Lua value of what the C call wrote through a reference parameter."""
    return _lua_value(api, p.type, p.name if api.kind(p.type) == "struct" else f"{p.name}[0]")


def _use_guard(opaque: OpaqueRef) -> str:
    """The assert every non-dtor method on the class begins with: using the object
    after release, or of a class whose opaque has no dtor to release it at all, is a
    caller bug, not a library result."""
    class_display = naming.upper_camel(opaque.class_name)
    reason = f"used after {opaque.dtor}" if opaque.dtor is not None else "has no handle"
    return f'assert(self._handle ~= nil, "{class_display} {reason}")'


def _type_check(api: Api, param: Param) -> tuple[tuple[str, ...], str]:
    """The Lua `type()` results a parameter's own argument may legitimately hold, and
    the words describing them for an assert message, keyed by the parameter's kind: a
    memory buffer (a string, or for an `out` count a number), a struct or a by-value
    opaque (a second handle), u64 (cdata is legitimate beside a number), or a plain
    number (u32 and every enum)."""
    if param.type == "memory":
        if param.ref == "out":
            return ("number",), "a number"
        return ("string",), "a string"
    kind = api.kind(param.type)
    if kind == "struct":
        return ("table", "cdata"), "a table or cdata"
    if kind == "opaque":
        return ("cdata",), "cdata"
    if param.type == "u64":
        return ("number", "cdata"), "a number or cdata"
    return ("number",), "a number"


def _visible_args(params: tuple[Param, ...]) -> list[Param]:
    """Parameters that appear as a Lua argument: every one but a non-memory `out`,
    which is allocated internally and returned instead."""
    return [p for p in params if p.type == "memory" or p.ref != "out"]


def _arg_asserts(api: Api, params: tuple[Param, ...], *, context: str) -> list[str]:
    """One `assert` per Lua-visible argument, in signature order, checking its type
    before any FFI allocation or call."""
    lines = []
    for p in _visible_args(params):
        name = _memory_arg(p) if p.type == "memory" else p.name
        types, expected = _type_check(api, p)
        condition = " or ".join(f'type({name}) == "{t}"' for t in types)
        lines.append(f'    assert({condition}, "{context}: {name} must be {expected}")\n')
    return lines


def _class(api: Api, opaque: OpaqueRef) -> str:
    class_display = naming.upper_camel(opaque.class_name)
    cls = f"M.{class_display}"
    ctor = next(f for f in api.functions if f.name == opaque.ctor)
    methods = [
        f
        for f in api.functions
        if f.name not in (opaque.ctor, opaque.dtor) and f.params and _is_opaque_value(f.params[0], opaque.name)
    ]
    method_names = [f.name for f in methods]
    if opaque.dtor is not None:
        method_names.append(opaque.dtor)
    out = [f"\n{cls} = {{}}\n{cls}.__index = {cls}\n"]
    out.append(_constructor(api, ctor, opaque, cls=cls, class_display=class_display, method_names=method_names))
    guard = _use_guard(opaque)
    out += [_method(api, fn, cls=cls, class_display=class_display, guard=guard) for fn in methods]
    if opaque.dtor is not None:
        out.append(_release(api, next(f for f in api.functions if f.name == opaque.dtor), cls=cls))
    return "".join(out)


def _memory_arg(p: Param) -> str:
    """The Lua-visible name in a memory parameter's own signature position: the
    parameter's name for `in`/`inout`, where the caller passes a string; its count
    name for `out`, where the caller says how many bytes to allocate instead."""
    return f"{p.name}_count" if p.ref == "out" else p.name


def _memory_alloc(p: Param) -> str | None:
    """The buffer a memory parameter's C pointer reaches: `out` allocates one sized by
    the caller's count; `inout` first captures the caller's string length in a local,
    since a cdata array has no length operator once it replaces the string under the
    same name, then copies the string into a buffer that size; `in` needs no buffer, a
    Lua string converts straight to `const void*`."""
    if p.ref == "in":
        return None
    if p.ref == "out":
        return f'    local {p.name} = ffi.new("uint8_t[?]", {p.name}_count)\n'
    return (
        f"    local {p.name}_count = #{p.name}\n"
        f'    local {p.name} = ffi.new("uint8_t[?]", {p.name}_count, {p.name})\n'
    )


def _memory_count(p: Param) -> str:
    """The byte count passed to the C call and read back for the returned string:
    `#` of the caller's string for `in`; the count local, either the caller's `out`
    argument or the one `_memory_alloc` captured for `inout`, otherwise."""
    return f"#{p.name}" if p.ref == "in" else f"{p.name}_count"


def _marshal(api: Api, params: tuple[Param, ...]) -> tuple[list[str], list[str], list[str], list[str]]:
    """Lua arguments, C call arguments, allocations and returned values. A `memory`
    parameter is a Lua string, never cdata the consumer sees: `in` passes the caller's
    string straight through; `out` and `inout` allocate a buffer and return its bytes
    as a string, exactly as a scalar `out`/`inout` is returned. Every other `out` is
    allocated and returned rather than taken."""
    args, call, allocs, rets = [], [], [], []
    for p in params:
        if p.type == "memory":
            args.append(_memory_arg(p))
            alloc = _memory_alloc(p)
            if alloc is not None:
                allocs.append(alloc)
            count = _memory_count(p)
            call += [p.name, count]
            if p.ref != "in":
                rets.append(f"ffi.string({p.name}, {count})")
            continue
        call.append(p.name)
        if p.ref != "out":
            args.append(p.name)
        if p.ref is not None:
            allocs.append(_alloc(api, p))
            if p.ref != "in":
                rets.append(_read_back(api, p))
    return args, call, allocs, rets


def _call(api: Api, fn: Function, call: list[str]) -> str:
    c_name = naming.function_name(api.namespace, fn.name)
    return f"    local result = lib.{c_name}({', '.join(call)})\n" + _result_check(api, fn)


def _result_check(api: Api, fn: Function) -> str:
    return f"    if result ~= M.{_ok_const(api, fn)} then\n        return nil, result\n    end\n"


def _constructor(
    api: Api, fn: Function, opaque: OpaqueRef, *, cls: str, class_display: str, method_names: list[str]
) -> str:
    """`new`, which caches every out parameter other than the handle on the object under
    its parameter name."""
    handle = next(p for p in fn.params if p.type == opaque.name and p.ref == "out")
    cached = [p for p in fn.params if p.ref == "out" and p is not handle]
    members = ["new", "_handle", *method_names, *(p.name for p in cached)]
    duplicate = next((m for m in members if members.count(m) > 1), None)
    if duplicate is not None:
        raise DefinitionError(f"Lua module: {cls}.{duplicate} would be defined more than once")
    args, call, allocs, _ = _marshal(api, fn.params)
    out = [
        _doc_lines(fn),
        f"function {cls}.new({', '.join(args)})\n",
        *_arg_asserts(api, fn.params, context=f"{class_display}.new"),
        *allocs,
    ]
    out.append(_call(api, fn, call))
    handle_value = f"{handle.name}[0]"
    if opaque.dtor is not None:
        dtor_call = f"lib.{naming.function_name(api.namespace, opaque.dtor)}"
        handle_value = f"ffi.gc({handle_value}, function(h) {dtor_call}(h) end)"
    out.append(f"    local self = setmetatable({{}}, {cls})\n    self._handle = {handle_value}\n")
    out += [f"    self.{p.name} = {_read_back(api, p)}\n" for p in cached]
    out.append("    return self, nil\nend\n")
    return "\n" + "".join(out)


def _method(api: Api, fn: Function, *, cls: str, class_display: str, guard: str) -> str:
    args, call, allocs, rets = _marshal(api, fn.params[1:])
    rets = rets or ["true"]
    return (
        f"\n{_doc_lines(fn)}function {cls}.{fn.name}({', '.join(['self', *args])})\n"
        f"    {guard}\n"
        + "".join(_arg_asserts(api, fn.params[1:], context=f"{class_display}.{fn.name}"))
        + "".join(allocs)
        + _call(api, fn, ["self._handle", *call])
        + f"    return {', '.join(rets)}, nil\nend\n"
    )


def _release(api: Api, dtor: Function, *, cls: str) -> str:
    """The dtor as an explicit method: detaches the GC finalizer if one is attached,
    releases whatever _handle holds (a nil handle reaches the library as NULL, and the
    library answers), and drops the handle whatever the result."""
    return (
        f"\n{_doc_lines(dtor)}function {cls}.{dtor.name}(self)\n"
        "    local handle = self._handle\n"
        "    if handle ~= nil then\n"
        "        ffi.gc(handle, nil)\n"
        "    end\n"
        f"    local result = lib.{naming.function_name(api.namespace, dtor.name)}(handle)\n"
        "    self._handle = nil\n"
        + _result_check(api, dtor)
        + "    return true, nil\nend\n"
    )
