"""The LuaJIT base module: ffi.cdef of the header, constants, raw functions and a class
per opaque ref that names a constructor."""

from api_gen import emit_c, naming
from api_gen.model import Api, DefinitionError, Function, OpaqueRef, Param

# Lua keywords plus the names generated code binds itself; a parameter named
# one of these would shadow or break the generated function.
_LUA_RESERVED = frozenset(
    "and break do else elseif end false for function goto if in local nil not or "
    "repeat return then true until while self result lib M ffi".split()
)


def module(api: Api, *, source_name: str, library: str) -> str:
    ns = api.namespace
    out = [
        f"-- GENERATED by vdev/api_gen from {source_name}; do not edit.\n",
        'local ffi = require("ffi")\n\n',
        _cdef(emit_c.cdef(api)),
        f'\nlocal lib = ffi.load("{library}")\n\nlocal M = {{}}\n\n',
    ]

    out += [f"M.{name} = {value}\n" for name, value in _constant_literals(api)]

    for typed in api.typed_consts:
        names = "".join(
            f'    [M.{c}] = "{c}",\n' for c in (naming.const_name(ns, e.key) for e in typed.entries)
        )
        out.append(
            f"\nlocal {typed.name}_names = {{\n{names}}}\n"
            f"function M.{typed.name}_to_str(value)\n    return {typed.name}_names[value]\nend\n"
        )
    returns = {f.returns for f in api.functions}
    if len(returns) == 1:
        out.append(f"M.error_to_str = M.{returns.pop()}_to_str\n")

    raw = "".join(f"    {f.name} = lib.{naming.function_name(ns, f.name)},\n" for f in api.functions)
    out.append(f"\nM.raw = {{\n{raw}}}\n")

    out += [_class(api, o) for o in api.opaque_refs if o.ctor is not None]

    out.append("\nreturn M\n")
    return "".join(out)


def _version_literal(api: Api) -> str:
    shifts = (24, 16, 8, 0)
    value = sum(b << s for b, s in zip(api.version, shifts))
    return f"0x{value:08x}"


def _bit_const_values(api: Api) -> dict[str, int]:
    """Each untyped_bit_const's value, in document order so a composed mask can OR
    the values of the earlier entries it names."""
    values: dict[str, int] = {}
    for c in api.bit_consts:
        values[c.key] = 1 << c.bit if c.bit is not None else 0
        for part in c.parts:
            values[c.key] |= values[part]
    return values


def _constant_literals(api: Api) -> list[tuple[str, str]]:
    """Every constant's (name, Lua literal), in the same order the C header defines them."""
    ns = api.namespace
    bit_values = _bit_const_values(api)
    literals = [(naming.version_const(ns), _version_literal(api))]
    literals += [
        (naming.const_name(ns, c.key), emit_c.int_literal(bit_values[c.key], c.format))
        for c in api.bit_consts
    ]
    literals += [
        (naming.const_name(ns, e.key), emit_c.int_literal(e.value, e.format))
        for t in api.typed_consts
        for e in t.entries
    ]
    return literals


def _cdef(text: str) -> str:
    level = 0
    while f"]{'=' * level}]" in text:
        level += 1
    eq = "=" * level
    return f"ffi.cdef[{eq}[\n{text}]{eq}]\n"


def _doc_lines(fn: Function) -> str:
    docs = [fn.docstring] if fn.docstring else []
    docs += [f"{p.name}: {p.docstring}" for p in fn.params if p.docstring]
    return "".join(f"-- {line}\n" for doc in docs for line in doc.splitlines())


def _ok_const(api: Api, fn: Function) -> str:
    typed = next(t for t in api.typed_consts if t.name == fn.returns)
    ok = next((e for e in typed.entries if e.value == 0), None)
    if ok is None:
        raise DefinitionError(f"Lua module: typed_const.{fn.returns} has no entry with value 0 for success")
    return naming.const_name(api.namespace, ok.key)


def _check_lua_names(fn: Function) -> None:
    for p in fn.params:
        if p.name in _LUA_RESERVED:
            raise DefinitionError(f"Lua module: function.{fn.name}.{p.name}: name is reserved in the Lua module")
        if p.type == "memory" and p.size is None:
            raise DefinitionError(f"Lua module: function.{fn.name}.{p.name}: a memory parameter needs 'size'")


def _is_opaque_value(param: Param, opaque: str) -> bool:
    return param.type == opaque and not (param.outref or param.inref)


def _lua_value(api: Api, type_name: str, expr: str) -> str:
    """u32 and enum values become Lua numbers; anything else (u64 included) stays cdata."""
    numeric = type_name == "u32" or api.kind(type_name) == "enum"
    return f"tonumber({expr})" if numeric else expr


def _class(api: Api, opaque: OpaqueRef) -> str:
    cls = f"M.{naming.lua_class(api.namespace, opaque.class_name)}"
    ctor = next(f for f in api.functions if f.name == opaque.ctor)
    methods = [
        f
        for f in api.functions
        if f.name not in (opaque.ctor, opaque.dtor) and f.params and _is_opaque_value(f.params[0], opaque.name)
    ]
    out = [f"\n{cls} = {{}}\n{cls}.__index = {cls}\n"]
    out.append(_constructor(api, ctor, opaque, cls=cls, method_names=[f.name for f in methods]))
    out += [_method(api, fn, cls=cls) for fn in methods]
    return "".join(out)


def _marshal(api: Api, params: tuple[Param, ...]) -> tuple[list[str], list[str], list[str], list[str]]:
    """Lua arguments, C call arguments, allocations and returned values for plain parameters."""
    sized_inputs = {p.size: p.name for p in params if p.type == "memory" and p.inref}
    args, call, allocs, rets = [], [], [], []
    for p in params:
        if p.name in sized_inputs:
            call.append(f"#{sized_inputs[p.name]}")
        elif not p.outref:
            args.append(p.name)
            call.append(p.name)
        elif p.type == "memory":
            allocs.append(f'    local {p.name} = ffi.new("uint8_t[?]", {p.size})\n')
            call.append(p.name)
            rets.append(f"ffi.string({p.name}, {p.size})")
        else:
            allocs.append(f'    local {p.name} = ffi.new("{emit_c.c_type(api, p.type)}[1]")\n')
            call.append(p.name)
            rets.append(_lua_value(api, p.type, f"{p.name}[0]"))
    return args, call, allocs, rets


def _call(api: Api, fn: Function, call: list[str]) -> str:
    c_name = naming.function_name(api.namespace, fn.name)
    return (
        f"    local result = lib.{c_name}({', '.join(call)})\n"
        f"    if result ~= M.{_ok_const(api, fn)} then\n        return nil, result\n    end\n"
    )


def _constructor(api: Api, fn: Function, opaque: OpaqueRef, *, cls: str, method_names: list[str]) -> str:
    """`new`, which caches every outref other than the handle on the object under its
    parameter name."""
    _check_lua_names(fn)
    handle = next(p for p in fn.params if p.type == opaque.name and p.outref)
    # (param, struct fields or None for a scalar) for each cached outref
    cached = []
    for p in fn.params:
        if not p.outref or p is handle:
            continue
        if p.type == "memory":
            raise DefinitionError(f"Lua module: function.{fn.name}.{p.name}: a constructor cannot cache a memory outref")
        struct = next((s for s in api.structs if s.name == p.type), None)
        cached.append((p, struct.fields if struct else None))
    members = ["new", "_handle", *method_names, *(p.name for p, _ in cached)]
    duplicate = next((m for m in members if members.count(m) > 1), None)
    if duplicate is not None:
        raise DefinitionError(f"Lua module: {cls}.{duplicate} would be defined more than once")
    # _marshal supplies the arguments and call; the constructor allocates its outrefs itself.
    args, call, _, _ = _marshal(api, fn.params)
    out = [_doc_lines(fn), f"function {cls}.new({', '.join(args)})\n"]
    for p in fn.params:
        if p.outref:
            shape = "" if api.kind(p.type) == "struct" else "[1]"
            out.append(f'    local {p.name} = ffi.new("{emit_c.c_type(api, p.type)}{shape}")\n')
    out.append(_call(api, fn, call))
    handle_value = f"{handle.name}[0]"
    if opaque.dtor is not None:
        handle_value = f"ffi.gc({handle_value}, lib.{naming.function_name(api.namespace, opaque.dtor)})"
    out.append(f"    local self = setmetatable({{}}, {cls})\n    self._handle = {handle_value}\n")
    for p, fields in cached:
        if fields is None:
            out.append(f"    self.{p.name} = {_lua_value(api, p.type, f'{p.name}[0]')}\n")
            continue
        copy = "".join(
            f"        {f.name} = {_lua_value(api, f.type, f'{p.name}.{f.name}')},\n" for f in fields
        )
        out.append(f"    self.{p.name} = {{\n{copy}    }}\n")
    out.append("    return self, nil\nend\n")
    return "\n" + "".join(out)


def _method(api: Api, fn: Function, *, cls: str) -> str:
    _check_lua_names(fn)
    args, call, allocs, rets = _marshal(api, fn.params[1:])
    rets = rets or ["true"]
    return (
        f"\n{_doc_lines(fn)}function {cls}.{fn.name}({', '.join(['self', *args])})\n"
        + "".join(allocs)
        + _call(api, fn, ["self._handle", *call])
        + f"    return {', '.join(rets)}, nil\nend\n"
    )
