"""The C header, and the declaration text the Lua module hands to ffi.cdef."""

from api_gen import naming
from api_gen.model import (
    Api, BitConst, EnumEntry, Function, Group, LiteralTerm, OpaqueRef, Param, Struct, Term, TypedConst,
)

C_KEYWORDS = frozenset(
    "auto break case char const continue default do double else enum extern float for goto if "
    "inline int long register restrict return short signed sizeof static struct switch typedef "
    "union unsigned void volatile while".split()
)
LABEL = "header"


def validate(api: Api) -> list[str]:
    """Every objection the header has to `api`: a name that is a C keyword, a constant
    whose C name is one of the header's own macros, and a typed enum value above the
    `int32_t` maximum, which a C17 enumerator cannot hold."""
    problems = [f"{where}: '{name}' is a C keyword" for where, name in api.names() if name in C_KEYWORDS]
    macros = header_macros(api.namespace)
    problems += [
        f"{where}: constant {naming.const_name(api.namespace, name)} is the header's own macro"
        for where, name in api.constant_names()
        if naming.const_name(api.namespace, name) in macros
    ]
    enumerator_max = naming.BASE_C_TYPES["i32"].max_value
    problems += [
        f"typed_const.{t.name}.{e.name}: value 0x{e.value:x} exceeds 0x{enumerator_max:x}; "
        "a C17 enumerator is an int"
        for t in api.typed_consts
        for e in t.entries
        if e.value > enumerator_max
    ]
    return [f"{LABEL}: {p}" for p in problems]


def c_type(api: Api, type_name: str) -> str:
    """C spelling of a definition type used by value."""
    if type_name in naming.BUILTIN_C_TYPES:
        return naming.BUILTIN_C_TYPES[type_name]
    return naming.type_name(api.namespace, type_name)


def int_literal(value: int, fmt: str) -> str:
    """An integer spelled as a Lua number, and as a C literal when non-negative: decimal,
    or lower-case unpadded hex."""
    if fmt == "hex":
        return f"-0x{-value:x}" if value < 0 else f"0x{value:x}"
    return str(value)


def typed_literal(value: int, fmt: str, base_type: str) -> str:
    """`value` as a C constant expression of `base_type`: the type's `<stdint.h>` macro
    around a non-negative literal spelled per `fmt`, the sign outside the macro. A
    negative literal would be the negation of a literal typed on its own, unsigned for
    hex beyond the signed maximum and wider than the type for the decimal minimum; the
    type's minimum, whose magnitude the type cannot hold, is the negated maximum less one."""
    base = naming.BASE_C_TYPES[base_type]
    if value >= 0:
        return f"{base.const_macro}({int_literal(value, fmt)})"
    if value == base.min_value:
        return f"(-{base.const_macro}({int_literal(base.max_value, fmt)}) - 1)"
    return f"(-{base.const_macro}({int_literal(-value, fmt)}))"


def c_params(api: Api, param: Param) -> list[tuple[str, str]]:
    """(C type, name) of each C parameter a definition parameter becomes: a `memory`
    parameter is the pointer and its byte count, every other parameter itself."""
    params = [(param_type(api, param), param.name)]
    if param.count_type is not None:
        params.append((naming.BUILTIN_C_TYPES[param.count_type], naming.count_param(param.name)))
    return params


def param_list(api: Api, fn: Function) -> str:
    """A function's C parameter list text, `void` for none: every parameter's `c_params()`
    pairs, joined in signature order. The one join the header's declaration and the
    stub's definition both use, so their signatures can never drift apart."""
    return ", ".join(f"{t} {n}" for p in fn.params for t, n in c_params(api, p)) or "void"


def param_type(api: Api, param: Param) -> str:
    if param.type == "memory":
        return "const void*" if param.ref == "in" else "void*"
    base = c_type(api, param.type)
    if param.ref == "in":
        return f"const {base}*"
    if param.ref is not None:
        return f"{base}*"
    return base


def header_macros(namespace: str) -> frozenset[str]:
    """Every macro the header defines or tests for itself, beside one per constant."""
    return frozenset({
        naming.c_api_macro(namespace), naming.api_macro(namespace),
        naming.impl_macro(namespace), naming.version_const(namespace),
    })


def emit(api: Api, *, source_name: str, stem: str, library: str | None) -> str:
    """The C header."""
    ns = api.namespace
    c_api, api_macro, impl = naming.c_api_macro(ns), naming.api_macro(ns), naming.impl_macro(ns)
    prelude = f"""\
/* GENERATED by vdev/api_gen from {source_name}; do not edit. */
#pragma once

#include <stdint.h>

#if defined(__cplusplus)
# define {c_api} extern "C"
#else
# define {c_api}
#endif

#if defined({impl})
# define {api_macro} {c_api} __attribute__((visibility("default")))
#else
# define {api_macro} {c_api}
#endif

"""
    text = prelude + declarations(api, function_prefix=f"{api_macro} ")
    if api.driver_data is not None:
        asserts = "".join(
            f'static_assert({naming.const_name(ns, key)} == {macro}, '
            f'"{naming.const_name(ns, key)} must match {macro}");\n'
            for key, macro in api.driver_data.const_pins
        )
        text += f"""\

#if defined({impl})
# include "{api.driver_data.header}"
/* ABI pins: the implementation build fails if a relayed constant disagrees with the driver's UAPI header */
# include <assert.h>
{asserts}#endif
"""
    return text


def cdef(api: Api) -> str:
    """The declaration text the Lua module hands to ffi.cdef: a typedef of its base type
    for each typed enum (not its body, since the Lua module carries constants as literals),
    opaque and struct declarations, and function declarations with no visibility macro.
    """
    typedefs = [
        f"typedef {naming.BASE_C_TYPES[t.base_type].c_type} {naming.type_name(api.namespace, t.name)};\n"
        for t in api.typed_consts
    ]
    return "\n".join(typedefs + [declarations(api, function_prefix="", constants=False)])


def declarations(api: Api, *, function_prefix: str, constants: bool = True) -> str:
    ns = api.namespace
    blocks = []
    if constants:
        version = f"{naming.BASE_C_TYPES['u32'].const_macro}(0x{api.version_value():08x})"
        blocks.append(_define(naming.version_const(ns), version, None))
        blocks += [_constant_group(api, g, operator="|") for g in api.bit_const_groups]
        blocks += [_constant_group(api, g, operator="+") for g in api.const_groups]
        blocks += [_typed_enum(api, t) for t in api.typed_consts]
        blocks += [
            _comment_line(g.docstring)
            + "".join(
                f'static const char {naming.const_name(ns, c.name)}[] = "{c.value}";{_trailing(c.docstring)}\n'
                for c in g.entries
            )
            for g in api.string_const_groups
        ]
    blocks += [_opaque(api, o) for o in api.opaque_refs]
    blocks += [_struct(api, s) for s in api.structs]
    if api.functions:
        blocks.append("".join(_function(api, f, function_prefix) for f in api.functions))
    return "\n".join(blocks)


def _comment_line(doc: str | None) -> str:
    return f"/* {doc} */\n" if doc else ""


def _trailing(doc: str | None) -> str:
    return f" /* {doc} */" if doc else ""


def _define(name: str, value: str, doc: str | None) -> str:
    return f"#define {name} {value}{_trailing(doc)}\n"


def _constant_group(api: Api, group: Group[BitConst] | Group[EnumEntry], *, operator: str) -> str:
    """A bit or plain group as one `#define` per entry under its docstring, each typed by
    the group's base type: a literal through its `<stdint.h>` macro, a single bit as that
    macro's 1 shifted, a composed entry as its terms joined by `operator`."""
    ns = api.namespace
    base = naming.BASE_C_TYPES[group.base_type]
    lines = []
    for c in group.entries:
        if c.parts:
            value = _sum(api, c.parts, operator=operator, base_type=group.base_type)
        elif isinstance(c, BitConst):
            value = f"({base.const_macro}(1) << {c.bit})"
        else:
            value = typed_literal(c.value, c.format, group.base_type)
        lines.append(_define(naming.const_name(ns, c.name), value, c.docstring))
    return _comment_line(group.docstring) + "".join(lines)


def _sum(api: Api, parts: tuple[Term, ...], *, operator: str, base_type: str) -> str:
    """A composed entry's value, symbolic and parenthesised; every term is of `base_type`,
    a literal through `typed_literal()`."""
    return "(" + f" {operator} ".join(
        typed_literal(p.value, p.format, base_type) if isinstance(p, LiteralTerm) else naming.const_name(api.namespace, p)
        for p in parts
    ) + ")"


def _typed_enum(api: Api, typed: TypedConst) -> str:
    ns = api.namespace
    name = naming.type_name(ns, typed.name)
    entries = typed.entries

    def value(e: EnumEntry) -> str:
        return int_literal(e.value, e.format) if e.value >= 0 else typed_literal(e.value, e.format, typed.base_type)

    lines = "".join(
        f"  {naming.const_name(ns, e.name)} = {value(e)}"
        f"{',' if i < len(entries) - 1 else ''}{_trailing(e.docstring)}\n"
        for i, e in enumerate(entries)
    )
    return f"{_comment_line(typed.docstring)}enum {name} {{\n{lines}}};\ntypedef enum {name} {name};\n"


def _opaque(api: Api, opaque: OpaqueRef) -> str:
    ns = api.namespace
    target = naming.opaque_struct(ns, opaque.name)
    return (
        f"{_comment_line(opaque.docstring)}struct {target};\n"
        f"typedef struct {target}* {naming.type_name(ns, opaque.name)};\n"
    )


def _struct(api: Api, struct: Struct) -> str:
    name = naming.type_name(api.namespace, struct.name)
    decls = [f"{c_type(api, f.type)} {f.name};" for f in struct.fields]
    width = max(len(d) for d in decls)
    lines = "".join(
        f"\t{d.ljust(width)} /* {f.docstring} */\n" if f.docstring else f"\t{d}\n"
        for d, f in zip(decls, struct.fields)
    )
    return f"{_comment_line(struct.docstring)}struct {name} {{\n{lines}}};\ntypedef struct {name} {name};\n"


def _function(api: Api, fn: Function, prefix: str) -> str:
    returns = c_type(api, fn.returns)
    name = naming.function_name(api.namespace, fn.name)
    return f"{_comment_line(' '.join(fn.docs()))}{prefix}{returns} {name}({param_list(api, fn)});\n"
