"""The ABI pin translation unit: static_asserts tying library constants to driver macros."""

from api_gen import naming
from api_gen.model import Api


def pins(api: Api, *, source_name: str, stem: str) -> str:
    lines = [f"/* GENERATED by vdev/api_gen from {source_name}; do not edit. */\n"]
    if api.driver_data is not None:
        lines.append(f'#include "{api.driver_data.header}"\n')
    lines.append(f'#include "{stem}.h"\n')
    if api.driver_data is not None and api.driver_data.const_pins:
        lines.append("\n")
        for key, macro in api.driver_data.const_pins:
            name = naming.const_name(api.namespace, key)
            lines.append(f'static_assert({name} == {macro}, "{name} must match {macro}");\n')
    return "".join(lines)
