"""A C++ implementation stub: every function defined, every body a placeholder failure."""

from api_gen import emit_c, naming
from api_gen.model import Api, DefinitionError, Function

UNSUPPORTED_KEY = "err_unsupported"


def stub(api: Api, *, source_name: str, stem: str) -> str:
    impl = naming.impl_macro(api.namespace)
    prelude = f"""\
// GENERATED by vdev/api_gen from {source_name}: implementation stub. Copy into lib/ once and replace every body; the generator never touches lib/.
#define {impl}
#include "{stem}.h"
#undef {impl}

#include <cerrno>
#include <cstdint>
#include <cstring>
"""
    return prelude + "".join("\n" + _definition(api, f) for f in api.functions)


def _definition(api: Api, fn: Function) -> str:
    ns = api.namespace
    params = ", ".join(f"{emit_c.param_type(api, p)} {p.name}" for p in fn.params) or "void"
    voids = "".join(f"  (void){p.name};\n" for p in fn.params)
    return (
        f"{naming.api_macro(ns)} {emit_c.c_type(api, fn.returns)} {naming.function_name(ns, fn.name)}({params}) {{\n"
        f"{voids}"
        f"  // replace: not implemented\n"
        f"  return {_failure(api, fn)};\n"
        f"}}\n"
    )


def _failure(api: Api, fn: Function) -> str:
    """C name of the return enum's `err_unsupported` entry, else its first nonzero entry."""
    entries = next(t for t in api.typed_consts if t.name == fn.returns).entries
    chosen = next((e for e in entries if e.key == UNSUPPORTED_KEY), None)
    chosen = chosen or next((e for e in entries if e.value != 0), None)
    if chosen is None:
        raise DefinitionError(
            f"function.{fn.name}.return: typed_const '{fn.returns}' has no nonzero entry: "
            "cannot pick a failure result for the stub"
        )
    return naming.const_name(api.namespace, chosen.key)
