"""The header-only C++20 wrapper: the constants, enums and structs under the namespace,
and a move-only class per opaque ref that names a constructor, forwarding inline to
the C functions."""

from api_gen import emit_c, naming
from api_gen.model import Api, DefinitionError, Function, OpaqueRef, Param

HANDLE_MEMBER = "handle_"


def wrapper(api: Api, *, source_name: str, stem: str) -> str:
    ns = api.namespace
    out = [
        f"// GENERATED by vdev/api_gen from {source_name}; do not edit.\n",
        "#pragma once\n\n",
        f'#include "{stem}.h"\n\n',
        "#include <utility>\n\n",
        f"namespace {ns} {{\n",
    ]
    classes = [o for o in api.opaque_refs if o.ctor is not None]
    const_keys = [naming.VERSION_KEY] + [c.key for c in (*api.bit_consts, *api.consts, *api.string_consts)]
    _check_unique(
        [naming.lua_const_name(k) for k in const_keys]
        + [naming.upper_camel(n) for n in [t.name for t in api.typed_consts] + [s.name for s in api.structs]]
        + [naming.upper_camel(o.class_name) for o in classes],
        f"C++ wrapper: namespace {ns}",
    )

    def constant(c_type: str, key: str) -> str:
        return f"inline constexpr {c_type} {naming.lua_const_name(key)} = {naming.const_name(ns, key)};\n"

    runs = [constant("uint32_t", naming.VERSION_KEY)]
    runs += [
        _comment(g.docstring) + "".join(constant(naming.BASE_C_TYPES[g.base_type], c.key) for c in g.entries)
        for g in (*api.bit_const_groups, *api.const_groups)
    ]
    if api.string_consts:
        runs.append("".join(constant("const char*", c.key) for c in api.string_consts))
    out += ["\n" + run for run in runs]
    out += [_enum(api, t.name) for t in api.typed_consts]
    if api.structs:
        out.append("\n" + "".join(f"using {naming.upper_camel(s.name)} = {naming.type_name(ns, s.name)};\n" for s in api.structs))
    out += [_class(api, o) for o in classes]
    out.append(f"\n}}  // namespace {ns}\n")
    return "".join(out)


def _check_unique(names: list[str], where: str) -> None:
    duplicate = next((n for n in names if names.count(n) > 1), None)
    if duplicate is not None:
        raise DefinitionError(f"{where}: {duplicate} would be defined more than once")


def _enum(api: Api, name: str) -> str:
    typed = next(t for t in api.typed_consts if t.name == name)
    cls = naming.upper_camel(name)
    keys = [naming.upper_camel(e.key) for e in typed.entries]
    _check_unique(keys, f"C++ wrapper: enum class {cls}")
    entries = "".join(
        f"  {k} = {naming.const_name(api.namespace, e.key)},\n" for k, e in zip(keys, typed.entries)
    )
    # One case per value, named by its last entry, as the Lua module's _to_str: duplicate case labels do not compile.
    by_value = {e.value: (k, e) for k, e in zip(keys, typed.entries)}
    cases = "".join(
        f'    case {cls}::{k}: return "{naming.lua_const_name(e.key)}";\n' for k, e in by_value.values()
    )
    return (
        f"\nenum class [[nodiscard]] {cls} : {naming.BASE_C_TYPES[typed.base_type]} {{\n{entries}}};\n\n"
        f"inline const char* to_string({cls} value) {{\n  switch (value) {{\n{cases}"
        f"  }}\n  return \"UNKNOWN_{name.upper()}\";\n}}\n"
    )


def _ref_type(api: Api, type_name: str) -> str:
    """C++ spelling of a non-memory type the C side reaches through a pointer or caches:
    the struct alias, else the C type."""
    if api.kind(type_name) == "struct":
        return naming.upper_camel(type_name)
    return emit_c.c_type(api, type_name)


def _marshal(api: Api, params: tuple[Param, ...], *, outrefs_are_locals: bool) -> tuple[list[str], list[str]]:
    """The C++ parameter list and the C call arguments. A `memory` parameter is forwarded
    exactly as the C header declares it, pointer and count; with `outrefs_are_locals`, a
    non-memory out parameter is the caller's local, passed by address and absent from the
    signature."""
    sig, call = [], []
    for p in params:
        if p.type == "memory":
            for c_type, name in emit_c.c_params(api, p):
                sig.append(f"{c_type} {name}")
                call.append(name)
        elif p.ref == "in":
            sig.append(f"const {_ref_type(api, p.type)}& {p.name}")
            call.append(f"&{p.name}")
        elif p.ref is not None:
            if not (outrefs_are_locals and p.ref == "out"):
                sig.append(f"{_ref_type(api, p.type)}& {p.name}")
            call.append(f"&{p.name}")
        elif api.kind(p.type) == "enum":
            sig.append(f"{naming.upper_camel(p.type)} {p.name}")
            call.append(f"{emit_c.c_type(api, p.type)}({p.name})")
        else:
            sig.append(f"{_ref_type(api, p.type)} {p.name}")
            call.append(p.name)
    return sig, call


def _doc(fn: Function) -> str:
    return "".join(f"  // {line}\n" for doc in fn.docs() for line in doc.splitlines())


def _c_call(api: Api, fn: Function, args: list[str]) -> str:
    ret = naming.upper_camel(fn.returns)
    return f"{ret}({naming.function_name(api.namespace, fn.name)}({', '.join(args)}))"


def _class(api: Api, opaque: OpaqueRef) -> str:
    cls = naming.upper_camel(opaque.class_name)
    handle_type = naming.type_name(api.namespace, opaque.name)
    ctor = next(f for f in api.functions if f.name == opaque.ctor)
    dtor = next((f for f in api.functions if f.name == opaque.dtor), None)
    methods = [
        f
        for f in api.functions
        if f not in (ctor, dtor)
        and f.params
        and f.params[0].type == opaque.name
        and f.params[0].ref is None
    ]
    handle = next(p for p in ctor.params if p.type == opaque.name and p.ref == "out")
    cached = [p for p in ctor.params if p.ref == "out" and p is not handle]
    _check_unique(
        [cls, "create", "handle", "release", HANDLE_MEMBER, *(f.name for f in methods), *(p.name for p in cached)],
        f"C++ wrapper: class {cls}",
    )

    ret = naming.upper_camel(ctor.returns)
    zero = next(e for e in next(t for t in api.typed_consts if t.name == ctor.returns).entries if e.value == 0)
    sig, call = _marshal(api, ctor.params, outrefs_are_locals=True)
    status = "status"
    while status in {p.name for p in ctor.params}:
        status += "_"
    locals_ = "".join(f"    {_ref_type(api, p.type)} {p.name}{{}};\n" for p in ctor.params if p.ref == "out")
    failure = f"{cls}({', '.join(['nullptr', *('{}' for _ in cached)])})"
    create = (
        f"{_doc(ctor)}"
        f"  [[nodiscard]] static {cls} create({', '.join([*sig, f'{ret}* result = nullptr'])}) {{\n"
        f"{locals_}"
        f"    const {ret} {status} = {_c_call(api, ctor, call)};\n"
        f"    if (result) {{\n      *result = {status};\n    }}\n"
        f"    if ({status} != {ret}::{naming.upper_camel(zero.key)}) {{\n      return {failure};\n    }}\n"
        f"    return {cls}({', '.join([handle.name, *(p.name for p in cached)])});\n"
        "  }\n"
    )

    release_guard = f"      if ({HANDLE_MEMBER}) {{\n        (void)release();\n      }}\n" if dtor is not None else ""
    reassign = "".join(f"      {p.name}_ = other.{p.name}_;\n" for p in cached)
    lifetime = (
        f"\n  {cls}(const {cls}&) = delete;\n"
        f"  {cls}& operator=(const {cls}&) = delete;\n"
        f"  {cls}({cls}&& other) noexcept\n"
        f"      : {', '.join([*(f'{p.name}_(other.{p.name}_)' for p in cached), f'{HANDLE_MEMBER}(std::exchange(other.{HANDLE_MEMBER}, nullptr))'])} {{}}\n"
        f"  {cls}& operator=({cls}&& other) noexcept {{\n"
        f"    if (this != &other) {{\n"
        f"{release_guard}"
        f"      {HANDLE_MEMBER} = std::exchange(other.{HANDLE_MEMBER}, nullptr);\n"
        f"{reassign}"
        f"    }}\n    return *this;\n  }}\n"
    )
    if dtor is not None:
        lifetime += (
            f"  ~{cls}() {{\n    if ({HANDLE_MEMBER}) {{\n      (void)release();\n    }}\n  }}\n"
        )
    lifetime += (
        f"\n  explicit operator bool() const {{ return {HANDLE_MEMBER} != nullptr; }}\n"
        f"  {handle_type} handle() const {{ return {HANDLE_MEMBER}; }}\n"
    )

    body = []
    for fn in methods:
        msig, mcall = _marshal(api, fn.params[1:], outrefs_are_locals=False)
        body.append(
            f"\n{_doc(fn)}  {naming.upper_camel(fn.returns)} {fn.name}({', '.join(msig)}) {{\n"
            f"    return {_c_call(api, fn, [HANDLE_MEMBER, *mcall])};\n  }}\n"
        )
    if dtor is not None:
        body.append(
            f"\n{_doc(dtor)}  {naming.upper_camel(dtor.returns)} release() {{\n"
            f"    return {_c_call(api, dtor, [f'std::exchange({HANDLE_MEMBER}, nullptr)'])};\n  }}\n"
        )

    accessors = "".join(
        f"  const {_ref_type(api, p.type)}& {p.name}() const {{ return {p.name}_; }}\n"
        if api.kind(p.type) == "struct"
        else f"  {_ref_type(api, p.type)} {p.name}() const {{ return {p.name}_; }}\n"
        for p in cached
    )
    private_members = "".join(f"  {_ref_type(api, p.type)} {p.name}_;\n" for p in cached)
    ctor_params = ", ".join([f"{handle_type} handle", *(f"const {_ref_type(api, p.type)}& {p.name}" for p in cached)])
    inits = ", ".join([*(f"{p.name}_({p.name})" for p in cached), f"{HANDLE_MEMBER}(handle)"])
    return (
        f"\n{_comment(opaque.docstring)}class {cls} {{\n public:\n{create}{lifetime}{''.join(body)}"
        + (f"\n{accessors}" if accessors else "")
        + f"\n private:\n  {cls}({ctor_params}) : {inits} {{}}\n\n{private_members}  {handle_type} {HANDLE_MEMBER};\n}};\n"
    )


def _comment(doc: str | None) -> str:
    return "".join(f"// {line}\n" for line in doc.splitlines()) if doc else ""
