"""The LuaJIT base module: ffi.cdef of the header, constants, raw functions and a class
per opaque ref that names a constructor."""

from pathlib import Path

from api_gen import naming
from api_gen.emitters import c
from api_gen.model import Api, BitConst, ClassShape, EnumEntry, Function, Group, OpaqueRef, Param, duplicates, single_bit_entries

_LUA_KEYWORDS = frozenset(
    "and break do else elseif end false for function goto if in local nil not or repeat return "
    "then true until while".split()
)
_GENERATED_NAMES = (
    "M", "ffi", "bit", "lib",
    "assert", "type", "tonumber", "setmetatable", "require", "string", "table",
    "self", "result", "handle", "h",
)
"""Every free name the generated text binds or references where a class function's
arguments are in scope: the module's locals, the globals it calls, and the locals a class
function binds. A parameter is the one definition name that becomes a bare Lua name, so
a parameter named like one of these would shadow it; the locals of a conversion function
(`value`, `names`) share no scope with a parameter."""
# LuaJIT hands a 64-bit integer back as cdata, since a Lua number is a double; every
# other builtin scalar, the floating-point ones included, converts to a number exactly.
_CDATA_INTEGERS = frozenset({"i64", "u64"})
LABEL = "lua"
# Every conversion answers nil as `tostring(nil)` does.
_NIL_CLAUSE = '    if value == nil then return "nil" end\n'


def validate(api: Api) -> list[str]:
    """Every objection the Lua module has to `api`: a name that is a Lua keyword, a
    parameter named like one of `_GENERATED_NAMES`, a bit flag beyond the signed 32-bit
    range, a module field (constant, conversion, `raw` or class) defined twice, and a class
    member defined twice."""
    problems = [f"{where}: '{name}' is a Lua keyword" for where, name in api.names() if name in _LUA_KEYWORDS]
    signed_max = naming.BASE_C_TYPES["i32"].max_value
    problems += [
        f"untyped_bit_const.{entry.name}: value 0x{entry.value:x} exceeds 0x{signed_max:x}; LuaJIT bit operations are "
        "signed 32-bit, so the flag would not equal its own masked result"
        for entry in api.bit_consts
        if entry.value > signed_max
    ]
    problems += [
        f"function.{fn.name}.{p.name}: '{p.name}' is a name the generated code uses"
        for fn in api.functions
        for p in fn.params
        if p.name in _GENERATED_NAMES
    ]
    classes = api.classes()
    fields = [(name, "a constant") for _, literals in _constant_sections(api) for name, _ in literals]
    fields += _conversion_names(api)
    fields.append(("raw", "the raw function table"))
    fields += [(naming.upper_camel(shape.opaque.class_name), "a class") for shape in classes]
    problems += [f"M.{name} would be both {' and '.join(whats)}" for name, whats in duplicates(fields).items()]
    for shape in classes:
        members = [("new", "the constructor"), ("_handle", "the handle")]
        members += [(f.name, f"function.{f.name}") for f in _class_methods(shape)]
        members += [(p.name, f"function.{shape.ctor.name}.{p.name}") for p in shape.cached]
        cls = naming.upper_camel(shape.opaque.class_name)
        problems += [f"M.{cls}.{m} would be both {' and '.join(whats)}" for m, whats in duplicates(members).items()]
    return [f"{LABEL}: {p}" for p in problems]


def output_path(*, stem: str, exercise: str) -> Path:
    return Path("binding") / f"{stem}.lua"


def emit(api: Api, *, source_name: str, stem: str, library: str | None) -> str:
    """The LuaJIT module, loading `library`, which the generator has resolved."""
    ns = api.namespace
    out = [
        f"-- GENERATED by vdev/api_gen from {source_name}; do not edit.\n",
        'local ffi = require("ffi")\n',
        'local bit = require("bit")\n' if any(g.to_string is not None for g in api.bit_const_groups) else "",
        "\n",
        _cdef(c.cdef(api)),
        f'\nlocal lib = ffi.load("{library}")\n\nlocal M = {{}}\n\n',
    ]

    for doc, literals in _constant_sections(api):
        out += [f"-- {line}\n" for line in (doc or "").splitlines()]
        out += [f"M.{name} = {value}\n" for name, value in literals]

    out += [_bit_to_string(g) for g in api.bit_const_groups if g.to_string is not None]
    out += [
        _lookup(naming.lua_to_string(g.to_string, typename=None), g.entries, unknown=naming.unknown_value_name(None))
        for g in api.const_groups
        if g.to_string is not None
    ]
    out += [
        _lookup(naming.lua_to_string(t.to_string, typename=t.name), t.entries, unknown=naming.unknown_value_name(t.name))
        for t in api.typed_consts
        if t.to_string is not None
    ]

    raw = "".join(f"    {f.name} = lib.{naming.function_name(ns, f.name)},\n" for f in api.functions)
    out.append(f"\nM.raw = {{\n{raw}}}\n")

    out += [_class(api, shape) for shape in api.classes()]

    out.append("\nreturn M\n")
    return "".join(out)


def _version_literal(api: Api) -> str:
    return f"0x{api.version_value():08x}"


def _constant_sections(api: Api) -> list[tuple[str | None, list[tuple[str, str]]]]:
    """Every constant's (name, Lua literal), in the same order the C header defines them,
    as (docstring, literals) sections: one per constant group, the rest undocumented.
    Every value is the model's already-resolved one; a composed entry's sum was computed,
    and a bit group's overlap-checked, once in model.py."""
    name = naming.unprefixed_const_name
    sections = [(None, [(name(naming.VERSION_KEY), _version_literal(api))])]
    sections += [
        (g.docstring, [(name(entry.name), c.int_literal(entry.value, entry.format)) for entry in g.entries])
        for g in api.bit_const_groups
    ]
    sections += [
        (g.docstring, [(name(entry.name), c.int_literal(entry.value, entry.format)) for entry in g.entries])
        for g in api.const_groups
    ]
    rest = [(name(e.name), c.int_literal(e.value, e.format)) for t in api.typed_consts for e in t.entries]
    sections.append((None, rest))
    sections += [
        (g.docstring, [(name(entry.name), f'"{entry.value}"') for entry in g.entries])
        for g in api.string_const_groups
    ]
    return sections


def _conversion_names(api: Api) -> list[tuple[str, str]]:
    """(module field, where the definition names it) for every `_to_string` conversion."""
    names = [
        (naming.lua_to_string(g.to_string, typename=None), f"{g.name}._to_string")
        for g in (*api.bit_const_groups, *api.const_groups)
        if g.to_string is not None
    ]
    names += [
        (naming.lua_to_string(t.to_string, typename=t.name), f"typed_const.{t.name}._to_string")
        for t in api.typed_consts
        if t.to_string is not None
    ]
    return names


def _lookup(name: str, entries: tuple[EnumEntry, ...], *, unknown: str) -> str:
    """A value-to-name conversion through a table, one key per value named by its last
    entry: the order a table constructor assigns repeated keys in is undefined."""
    by_value = {e.value: naming.unprefixed_const_name(e.name) for e in entries}
    keys = "".join(f'    [M.{key}] = "{key}",\n' for key in by_value.values())
    table = naming.lua_lookup_table(name)
    return (
        f"\nlocal {table} = {{\n{keys}}}\n"
        f'function M.{name}(value)\n{_NIL_CLAUSE}    return {table}[value] or "{unknown}"\nend\n'
    )


def _bit_to_string(group: Group[BitConst]) -> str:
    """Each single-bit entry present in the value, in document order, joined with `|`, and
    whatever bits remain as one final hex term of their 32-bit pattern."""
    flags = "".join(
        f"    if bit.band(value, M.{k}) ~= 0 then\n"
        f'        names[#names + 1] = "{k}"\n'
        f"        value = bit.band(value, bit.bnot(M.{k}))\n"
        "    end\n"
        for k in (naming.unprefixed_const_name(entry.name) for entry in single_bit_entries(group))
    )
    return (
        f"\nfunction M.{naming.lua_to_string(group.to_string, typename=None)}(value)\n"
        f"{_NIL_CLAUSE}"
        f'    if value == 0 then return "{naming.NO_FLAGS}" end\n'
        "    local names = {}\n"
        f"{flags}"
        "    if value ~= 0 then\n"
        '        names[#names + 1] = string.format("0x%x", value % 0x100000000)\n'
        "    end\n"
        '    return table.concat(names, "|")\n'
        "end\n"
    )


def _cdef(text: str) -> str:
    return f"ffi.cdef[[\n{text}]]\n"


def _doc_lines(fn: Function) -> str:
    return "".join(f"-- {line}\n" for doc in fn.docs() for line in doc.splitlines())


def _unboxed(api: Api, type_name: str) -> str:
    """The type a Lua caller passes and receives for `type_name`: a boxed scalar's base
    type, else the type itself."""
    return next((b.base_type for b in api.boxed_scalars if b.name == type_name), type_name)


def _lua_value(api: Api, type_name: str, expr: str, *, indent: str = "    ") -> str:
    """Enum values and builtins narrower than 64 bits become Lua numbers, a struct a
    table of its fields converted the same way (nested structs included); 64-bit and
    opaque values stay cdata. A boxed scalar, reached only as a struct field here, is a
    copy of its FFI struct: indexing a struct field of struct type yields a reference into
    the parent, which the GC does not keep alive. `indent` is the indentation of the line
    the expression starts on."""
    kind = api.kind(type_name)
    if kind == "boxed":
        return f'ffi.new("{c.c_type(api, type_name)}", {expr})'
    if kind == "struct":
        fields = next(s for s in api.structs if s.name == type_name).fields
        inner = indent + "    "
        body = "".join(
            f"{inner}{f.name} = {_lua_value(api, f.type, f'{expr}.{f.name}', indent=inner)},\n" for f in fields
        )
        return f"{{\n{body}{indent}}}"
    as_number = kind == "enum" or (kind == "builtin" and type_name not in _CDATA_INTEGERS)
    return f"tonumber({expr})" if as_number else expr


def _box(api: Api, type_name: str) -> str:
    """The ffi.new type for a value the C side reaches through a pointer: a struct or
    boxed scalar itself, anything else a one-element array."""
    c_type = c.c_type(api, type_name)
    return c_type if api.kind(type_name) in ("boxed", "struct") else f"{c_type}[1]"


def _alloc(api: Api, p: Param) -> str:
    """The cdata a non-memory reference parameter's C pointer reaches: an `in` or `inout`
    value arrives as a Lua value (a table or cdata for a struct) and is copied in; an
    `out` value starts zeroed. An `_optional` `in` or `inout` parameter builds the cdata
    only when the caller's value is non-nil; `nil` passes straight through, so the FFI
    turns it into a null pointer. A constructor's cached `out` parameter (also `out`
    here) ignores `_optional`, since the binding always supplies it."""
    box = _box(api, p.type)
    if p.optional and p.ref != "out":
        return f'    local {p.name} = {p.name} ~= nil and ffi.new("{box}", {p.name}) or nil\n'
    init = "" if p.ref == "out" else f", {p.name}"
    return f'    local {p.name} = ffi.new("{box}"{init})\n'


def _read_back(api: Api, p: Param) -> str:
    """The Lua value of what the C call wrote through a reference parameter. An
    `_optional` `inout` parameter reads back `nil` when the caller's own value was nil,
    since `_alloc` never built a pointer for the call to write through. A boxed scalar
    reads back its base type's value from `.value`."""
    kind = api.kind(p.type)
    if kind == "boxed":
        value = _lua_value(api, _unboxed(api, p.type), f"{p.name}.value")
    else:
        value = _lua_value(api, p.type, p.name if kind == "struct" else f"{p.name}[0]")
    if p.optional and p.ref != "out":
        return f"({p.name} ~= nil and {value} or nil)"
    return value


def _use_guard(opaque: OpaqueRef) -> str:
    """The assert every non-dtor method on the class begins with: using the object
    after release, or of a class whose opaque has no dtor to release it at all, is a
    caller bug, not a library result."""
    class_display = naming.upper_camel(opaque.class_name)
    reason = f"used after {opaque.dtor}" if opaque.dtor is not None else "has no handle"
    return f'assert(self._handle ~= nil, "{class_display} {reason}")'


def _type_check(api: Api, param: Param, name: str) -> tuple[str, str]:
    """The Lua condition `name`'s argument must satisfy, and the words describing the
    expected value for an assert message, keyed by the parameter's kind: a memory
    buffer (a string, or for an `out` count a number), a struct (a table or its own
    cdata type), a by-value opaque (its own cdata type, never bare `cdata`), a 64-bit
    builtin (a number or 64-bit cdata, since a literal like `48ULL` may be `uint64_t`
    or `int64_t`), or a plain number (every narrower builtin and every enum); a boxed
    scalar is checked as its base type, which is what the caller passes. An
    `_optional` parameter's condition also admits `nil`, and its expected text gains
    an " or nil" suffix; the loader refuses `_optional` on a by-value parameter and on a
    `memory` one other than `_ref = "in"`, so neither reaches here."""
    if param.type == "memory":
        if param.ref == "out":
            return f'type({name}) == "number"', "a number"
        condition, expected = f'type({name}) == "string"', "a string"
        if param.optional:
            condition, expected = f"{name} == nil or {condition}", f"{expected} or nil"
        return condition, expected
    kind = api.kind(param.type)
    if kind == "struct":
        c_type = c.c_type(api, param.type)
        condition, expected = f'type({name}) == "table" or ffi.istype("{c_type}", {name})', f"a table or {c_type}"
    elif kind == "opaque":
        c_type = c.c_type(api, param.type)
        condition, expected = f'ffi.istype("{c_type}", {name})', f"a {c_type}"
    elif _unboxed(api, param.type) in _CDATA_INTEGERS:
        condition = f'type({name}) == "number" or ffi.istype("uint64_t", {name}) or ffi.istype("int64_t", {name})'
        expected = "a number or 64-bit cdata"
    else:
        condition, expected = f'type({name}) == "number"', "a number"
    if param.optional:
        condition, expected = f"{name} == nil or {condition}", f"{expected} or nil"
    return condition, expected


def _visible_args(params: tuple[Param, ...]) -> list[Param]:
    """Parameters that appear as a Lua argument: every one but a non-memory `out`,
    which is allocated internally and returned instead."""
    return [p for p in params if p.type == "memory" or p.ref != "out"]


def _arg_asserts(api: Api, params: tuple[Param, ...], *, context: str) -> list[str]:
    """One `assert` per Lua-visible argument, in signature order, checking its type
    before any FFI allocation or call."""
    lines = []
    for p in _visible_args(params):
        name = _memory_arg(p) if p.type == "memory" else p.name
        condition, expected = _type_check(api, p, name)
        lines.append(f'    assert({condition}, "{context}: {name} must be {expected}")\n')
    return lines


def _class_methods(shape: ClassShape) -> tuple[Function, ...]:
    """Every method of the class, the dtor's included."""
    return shape.methods if shape.dtor is None else (*shape.methods, shape.dtor)


def _class(api: Api, shape: ClassShape) -> str:
    class_display = naming.upper_camel(shape.opaque.class_name)
    cls = f"M.{class_display}"
    out = [f"\n{cls} = {{}}\n{cls}.__index = {cls}\n"]
    out.append(_constructor(api, shape, cls=cls, class_display=class_display))
    guard = _use_guard(shape.opaque)
    out += [_method(api, fn, cls=cls, class_display=class_display, guard=guard) for fn in shape.methods]
    if shape.dtor is not None:
        out.append(_release(api, shape.dtor, cls=cls))
    return "".join(out)


def _memory_arg(p: Param) -> str:
    """The Lua-visible name in a memory parameter's own signature position: the
    parameter's name for `in`/`inout`, where the caller passes a string; its count
    name for `out`, where the caller says how many bytes to allocate instead."""
    return naming.count_param(p.name) if p.ref == "out" else p.name


def _memory_alloc(p: Param) -> str | None:
    """The buffer a memory parameter's C pointer reaches: `out` allocates one sized by
    the caller's count; `inout` first captures the caller's string length in a local,
    since a cdata array has no length operator once it replaces the string under the
    same name, then copies the string into a buffer that size; `in` needs no buffer, a
    Lua string converts straight to `const void*`."""
    count = naming.count_param(p.name)
    if p.ref == "in":
        return None
    if p.ref == "out":
        return f'    local {p.name} = ffi.new("uint8_t[?]", {count})\n'
    return (
        f"    local {count} = #{p.name}\n"
        f'    local {p.name} = ffi.new("uint8_t[?]", {count}, {p.name})\n'
    )


def _memory_count(p: Param) -> str:
    """The byte count passed to the C call and read back for the returned string:
    `#` of the caller's string for `in`; the count local, either the caller's `out`
    argument or the one `_memory_alloc` captured for `inout`, otherwise. An `_optional`
    `in` argument's count is 0 when the caller passed `nil` instead of a string."""
    if p.ref != "in":
        return naming.count_param(p.name)
    if p.optional:
        return f"({p.name} and #{p.name} or 0)"
    return f"#{p.name}"


def _marshal(api: Api, params: tuple[Param, ...]) -> tuple[list[str], list[str], list[str], list[str]]:
    """Lua arguments, C call arguments, allocations and returned values. A `memory`
    parameter is a Lua string, never cdata the consumer sees: `in` passes the caller's
    string straight through; `out` and `inout` allocate a buffer and return its bytes
    as a string, exactly as a scalar `out`/`inout` is returned. Every other `out` is
    allocated and returned rather than taken. A boxed scalar by value arrives as its base
    type's value and is boxed for the call."""
    args, call, allocs, rets = [], [], [], []
    for p in params:
        if p.type == "memory":
            args.append(_memory_arg(p))
            alloc = _memory_alloc(p)
            if alloc is not None:
                allocs.append(alloc)
            count = _memory_count(p)
            call += [p.name, count]
            if p.ref != "in":
                rets.append(f"ffi.string({p.name}, {count})")
            continue
        call.append(p.name)
        if p.ref != "out":
            args.append(p.name)
        if p.ref is None and api.kind(p.type) == "boxed":
            allocs.append(f'    local {p.name} = ffi.new("{c.c_type(api, p.type)}", {p.name})\n')
        if p.ref is not None:
            allocs.append(_alloc(api, p))
            if p.ref != "in":
                rets.append(_read_back(api, p))
    return args, call, allocs, rets


def _call(api: Api, fn: Function, call: list[str]) -> str:
    c_name = naming.function_name(api.namespace, fn.name)
    return f"    local result = lib.{c_name}({', '.join(call)})\n" + _result_check(api, fn)


def _result_check(api: Api, fn: Function) -> str:
    ok = naming.unprefixed_const_name(api.success_entry(fn).name)
    return f"    if result ~= M.{ok} then\n        return nil, result\n    end\n"


def _constructor(api: Api, shape: ClassShape, *, cls: str, class_display: str) -> str:
    """`new`, which caches every out parameter other than the handle on the object under
    its parameter name."""
    fn, opaque = shape.ctor, shape.opaque
    args, call, allocs, _ = _marshal(api, fn.params)
    out = [
        _doc_lines(fn),
        f"function {cls}.new({', '.join(args)})\n",
        *_arg_asserts(api, fn.params, context=f"{class_display}.new"),
        *allocs,
    ]
    out.append(_call(api, fn, call))
    handle_value = f"{shape.handle.name}[0]"
    if opaque.dtor is not None:
        dtor_call = f"lib.{naming.function_name(api.namespace, opaque.dtor)}"
        handle_value = f"ffi.gc({handle_value}, function(h) {dtor_call}(h) end)"
    out.append(f"    local self = setmetatable({{}}, {cls})\n    self._handle = {handle_value}\n")
    out += [f"    self.{p.name} = {_read_back(api, p)}\n" for p in shape.cached]
    out.append("    return self, nil\nend\n")
    return "\n" + "".join(out)


def _method(api: Api, fn: Function, *, cls: str, class_display: str, guard: str) -> str:
    args, call, allocs, rets = _marshal(api, fn.params[1:])
    rets = rets or ["true"]
    return (
        f"\n{_doc_lines(fn)}function {cls}.{fn.name}({', '.join(['self', *args])})\n"
        f"    {guard}\n"
        + "".join(_arg_asserts(api, fn.params[1:], context=f"{class_display}.{fn.name}"))
        + "".join(allocs)
        + _call(api, fn, ["self._handle", *call])
        + f"    return {', '.join(rets)}, nil\nend\n"
    )


def _release(api: Api, dtor: Function, *, cls: str) -> str:
    """The dtor as an explicit method: detaches the GC finalizer if one is attached,
    releases whatever _handle holds, or else a NULL handle of its own cdata type (the
    FFI call takes real cdata, never a bare Lua nil; the library answers a NULL handle
    the same as any other), and drops the handle whatever the result."""
    opaque_type = c.c_type(api, dtor.params[0].type)
    return (
        f"\n{_doc_lines(dtor)}function {cls}.{dtor.name}(self)\n"
        f'    local handle = self._handle or ffi.new("{opaque_type}")\n'
        "    if self._handle ~= nil then\n"
        "        ffi.gc(self._handle, nil)\n"
        "    end\n"
        f"    local result = lib.{naming.function_name(api.namespace, dtor.name)}(handle)\n"
        "    self._handle = nil\n"
        + _result_check(api, dtor)
        + "    return true, nil\nend\n"
    )
