"""A C++ implementation stub: every function defined, every body `return {};` to be replaced."""

from pathlib import Path

from api_gen import naming
from api_gen.emitters import c, cpp
from api_gen.model import Api, Function

LABEL = "stub"


def validate(api: Api) -> list[str]:
    """Every objection the stub has to `api`: a name that is a C++ keyword, and a parameter
    named like a type its signatures spell."""
    return [f"{LABEL}: {o}" for o in cpp.cpp_keyword_objections(api) + c.parameter_type_objections(api)]


def output_path(*, name: str, project: str) -> Path:
    return Path("stub") / f"{name}.cpp"


def emit(api: Api, *, source_name: str, name: str, library: str | None, project: str) -> str:
    impl = naming.impl_macro(api.namespace)
    prelude = f"""\
// GENERATED by vdev/api_gen from {source_name}: implementation stub. Copy beside the implementation once and replace every body; the generator never touches it afterwards.
#define {impl}
#include "{name}.h"
#undef {impl}

#include <cerrno>
#include <cstdint>
#include <cstring>
"""
    return prelude + "".join("\n" + _definition(api, f) for f in api.functions)


def _definition(api: Api, fn: Function) -> str:
    ns = api.namespace
    voids = "".join(f"  (void){n};\n" for p in fn.params for _, n in c.c_params(api, p))
    return (
        f"{naming.api_macro(ns)} {c.c_type(api, fn.returns)} {naming.function_name(ns, fn.name)}"
        f"({c.param_list(api, fn)}) {{\n"
        f"{voids}"
        "  // replace: not implemented\n"
        "  return {};\n"
        "}\n"
    )
