"""A Rust implementation stub: a crate root that includes the regenerated relay and
defines, for every function, the implementation the relay calls, each body returning
`Ok(())`, to be replaced."""

from pathlib import Path

from api_gen import naming
from api_gen.emitters import rust
from api_gen.model import Api, Function, duplicate_objections

LABEL = "rust_stub"


def validate(api: Api) -> list[str]:
    """Every objection the Rust stub has to `api`: a name that is a Rust keyword; a
    function or parameter name rustc's `non_snake_case` refuses, the implementation
    functions being plain `fn`s; and a name it imports whose UpperCamel rendering is a
    keyword or a prelude name its text spells, which the import would shadow."""
    names = [(f"function.{fn.name}", fn.name) for fn in api.functions]
    names += [(f"function.{fn.name}.{p.name}", p.name) for fn in api.functions for p in fn.params]
    objections = rust.rust_keyword_objections(api) + rust.snake_case_objections(names)
    imported = _imported(api)
    objections += rust.camel_keyword_objections(imported)
    module = rust.prelude_names() + [(where, naming.upper_camel(name)) for where, name in imported]
    objections += duplicate_objections(module, "module scope")
    return [f"{LABEL}: {o}" for o in objections]


def output_path(*, name: str, project: str) -> Path:
    return Path("stub") / f"{name}.rs"


def emit(api: Api, *, source_name: str, name: str, library: str | None, project: str) -> str:
    """The Rust implementation stub, as rustfmt lays it out."""
    blocks = [f'pub mod abi {{\n    include!(concat!(env!("API_GEN_RUST_DIR"), "/{rust.abi_file_name(name)}"));\n}}\n']
    imports = _imports(api)
    if imports:
        blocks.append(f"use abi::{{{', '.join(imports)}}};\n")
    blocks += [_definition(api, fn) for fn in api.functions]
    return rust.rustfmt(
        f"// GENERATED by vdev/api_gen from {source_name}: implementation stub. "
        "Copy beside the implementation once and replace every body; the generator never touches it afterwards.\n"
        + "".join("\n" + b for b in blocks)
    )


def _imported(api: Api) -> list[tuple[str, str]]:
    """(where, name) of each type the signatures name from the relay by its UpperCamel
    name: a boxed scalar or struct parameter's re-export, and each return enum."""
    used = {p.type for fn in api.functions for p in fn.params if p.type != "memory" and api.kind(p.type) in ("boxed", "struct")}
    used |= {fn.returns for fn in api.functions}
    return [(where, name) for where, name in rust.type_names(api) if name in used]


def _imports(api: Api) -> list[str]:
    """What the signatures name from the relay: `ffi` for an enum or opaque parameter, and
    `_imported()`'s UpperCamel names, in no order: rustfmt sorts the `use` list."""
    kinds = {api.kind(p.type) for fn in api.functions for p in fn.params if p.type != "memory"}
    names = [naming.upper_camel(name) for _, name in _imported(api)]
    return (["ffi"] if kinds & {"enum", "opaque"} else []) + names


def _definition(api: Api, fn: Function) -> str:
    """One implementation function: its docstring lines, the signature the relay pins, and
    a body discarding each parameter and returning `Ok(())`."""
    params = ", ".join(f"{p.name}: {rust.implementation_type(api, p)}" for p in fn.params)
    return (
        rust.function_docs(fn)
        + rust.many_arguments_allow(len(fn.params))
        + f"pub fn {fn.name}({params}) -> Result<(), {naming.upper_camel(fn.returns)}> {{\n"
        + "".join(f"    let _ = {p.name};\n" for p in fn.params)
        + "    // replace: not implemented\n"
        + "    Ok(())\n"
        + "}\n"
    )
