// AI generated (Claude Fable 5.1 via Claude Code); fate TBD, likely removed and hand re-implemented.
// Implements the tcdl API generated by vdev/api_gen from tcdl_api.adef.toml over the driver's ioctls.

pub mod abi {
    include!(concat!(env!("API_GEN_RUST_DIR"), "/tcdl_api_abi.rs"));
}

use abi::{DmaOffset, Info, OpResult, ffi, wrapped_api};
use std::ffi::{CStr, OsStr, OsString, c_int, c_ulong, c_void};
use std::fs::OpenOptions;
use std::os::fd::{AsRawFd, IntoRawFd};
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::OpenOptionsExt;
use std::ptr;

unsafe extern "C" {
    fn ioctl(fd: c_int, request: c_ulong, ...) -> c_int;
    fn close(fd: c_int) -> c_int;
}

const DEVICE_NAME_BASE: &CStr = match CStr::from_bytes_with_nul(wrapped_api::TCD_DEVICE_NAME_BASE) {
    Ok(name) => name,
    Err(_) => panic!("TCD_DEVICE_NAME_BASE is not a C string"),
};

const HANDLE_OBFUSC: usize = 0x8_6753_0900;

fn fd2h(fd: c_int) -> ffi::tcdl_handle {
    // A handle is never dereferenced: the address carries the fd and nothing else.
    ptr::without_provenance_mut(fd as usize ^ HANDLE_OBFUSC)
}

fn h2fd(h: ffi::tcdl_handle) -> Result<c_int, OpResult> {
    if h.is_null() {
        return Err(OpResult::ErrInvalidHandle);
    }
    c_int::try_from(h.addr() ^ HANDLE_OBFUSC).map_err(|_| OpResult::ErrInvalidHandle)
}

fn errno_to_result() -> OpResult {
    let errno = std::io::Error::last_os_error().raw_os_error();
    match errno.and_then(|e| u32::try_from(e).ok()) {
        Some(wrapped_api::ETIMEDOUT) => OpResult::ErrTimedout,
        Some(wrapped_api::EOPNOTSUPP) => OpResult::ErrUnsupported,
        Some(wrapped_api::EINVAL) => OpResult::ErrMisaligned,
        Some(wrapped_api::EFAULT) => OpResult::ErrInvalidAddress,
        Some(wrapped_api::ENOTRECOVERABLE) => OpResult::ErrDeviceDead,
        _ => OpResult::ErrCommFailed,
    }
}

/// Issues `request` on `fd`, mapping a failure through errno.
///
/// # Safety
///
/// `arg` is null or points to memory valid for the access `request` encodes, for the call.
unsafe fn tcd_ioctl(
    fd: c_int,
    request: wrapped_api::tcd_ioc_req,
    arg: *mut c_void,
) -> Result<(), OpResult> {
    // SAFETY: the caller upholds `arg`'s validity for `request`; an invalid fd fails with EBADF.
    if unsafe { ioctl(fd, c_ulong::from(request), arg) } < 0 {
        return Err(errno_to_result());
    }
    Ok(())
}

/// multiple devices and multiple access to single device supported. info out param is optional.
pub fn create_device(
    index: u32,
    phtcd: Option<&mut ffi::tcdl_handle>,
    info: Option<&mut Info>,
) -> Result<(), OpResult> {
    let phtcd = phtcd.ok_or(OpResult::ErrInvalidAddress)?;
    *phtcd = ptr::null_mut();

    let mut path = OsString::from("/dev/");
    path.push(OsStr::from_bytes(DEVICE_NAME_BASE.to_bytes()));
    path.push(index.to_string());
    let file = OpenOptions::new()
        .read(true)
        .write(true)
        .custom_flags(wrapped_api::O_SYNC as c_int)
        .open(path)
        .map_err(|_| OpResult::ErrNoDevice)?;

    let mut tcd = wrapped_api::tcd_info {
        abi_version: 0,
        device_id: 0,
        dma_buf_size: 0,
        dma_alignment: 0,
        flags: 0,
    };
    let tcd_ptr = ptr::from_mut(&mut tcd).cast();
    // SAFETY: TCD_IOC_INFO writes one `tcd_info`, which `tcd_ptr` points to.
    unsafe { tcd_ioctl(file.as_raw_fd(), wrapped_api::TCD_IOC_INFO_REQ, tcd_ptr) }?;

    if let Some(info) = info {
        *info = Info {
            api_version: ffi::TCDL_API_VERSION,
            device_idx: index,
            dma_buf_size: tcd.dma_buf_size,
            dma_alignment: tcd.dma_alignment,
            device_caps: tcd.flags,
        };
    }

    *phtcd = fd2h(file.into_raw_fd());
    Ok(())
}

/// double destroy will return an error but won't crash.
pub fn destroy_device(htcd: ffi::tcdl_handle) -> Result<(), OpResult> {
    let fd = h2fd(htcd)?;
    // SAFETY: close takes no memory; a closed or foreign fd fails with EBADF.
    if unsafe { close(fd) } != 0 {
        return Err(OpResult::ErrInvalidHandle);
    }
    Ok(())
}

/// result is ok or device_dead
pub fn check_alive(htcd: ffi::tcdl_handle) -> Result<(), OpResult> {
    let fd = h2fd(htcd)?;
    // SAFETY: TCD_IOC_LIVENESS takes a null argument.
    unsafe { tcd_ioctl(fd, wrapped_api::TCD_IOC_LIVENESS_REQ, ptr::null_mut()) }
        .map_err(|_| OpResult::ErrDeviceDead)
}

pub fn compute_factorial(
    htcd: ffi::tcdl_handle,
    arg: u32,
    fact: Option<&mut u32>,
) -> Result<(), OpResult> {
    let fd = h2fd(htcd)?;
    let fact = fact.ok_or(OpResult::ErrInvalidAddress)?;
    let mut value = arg;
    let value_ptr = ptr::from_mut(&mut value).cast();
    // SAFETY: TCD_IOC_COMPUTE reads and writes one `u32`, which `value_ptr` points to.
    unsafe { tcd_ioctl(fd, wrapped_api::TCD_IOC_COMPUTE_REQ, value_ptr) }?;
    *fact = value;
    Ok(())
}

/// Moves `count` bytes at `ubuf` to or from the device at `offset` with `request`.
///
/// # Safety
///
/// `ubuf` is valid for `count` bytes of the access `request` makes, for the call.
unsafe fn dma(
    fd: c_int,
    request: wrapped_api::tcd_ioc_req,
    offset: DmaOffset,
    ubuf: *const u8,
    count: usize,
) -> Result<(), OpResult> {
    let mut req = wrapped_api::tcd_dma_req {
        ubuf: ubuf.expose_provenance() as u64,
        dev_offset: offset.0,
        count: count as u64,
    };
    let req_ptr = ptr::from_mut(&mut req).cast();
    // SAFETY: `req_ptr` points to the `tcd_dma_req` the request reads; the caller upholds `ubuf`.
    unsafe { tcd_ioctl(fd, request, req_ptr) }
}

/// be sure to check offset and size against dma_alignment
pub fn dma_to_device(
    htcd: ffi::tcdl_handle,
    dst_dma_offset: DmaOffset,
    psrc: Option<&[u8]>,
) -> Result<(), OpResult> {
    let fd = h2fd(htcd)?;
    let src = psrc.ok_or(OpResult::ErrInvalidAddress)?;
    // SAFETY: the driver only reads `src`, which is valid for its length.
    unsafe {
        dma(
            fd,
            wrapped_api::TCD_IOC_DMA_TO_DEVICE_REQ,
            dst_dma_offset,
            src.as_ptr(),
            src.len(),
        )
    }
}

/// be sure to check offset and size against dma_alignment
pub fn dma_from_device(
    htcd: ffi::tcdl_handle,
    src_dma_offset: DmaOffset,
    pdst: Option<&mut [u8]>,
) -> Result<(), OpResult> {
    let fd = h2fd(htcd)?;
    let dst = pdst.ok_or(OpResult::ErrInvalidAddress)?;
    // SAFETY: the driver writes `dst`, which is exclusively borrowed and valid for its length.
    unsafe {
        dma(
            fd,
            wrapped_api::TCD_IOC_DMA_FROM_DEVICE_REQ,
            src_dma_offset,
            dst.as_mut_ptr(),
            dst.len(),
        )
    }
}
