// GENERATED by vdev/api_gen from xy_api.adef.toml: implementation stub. Copy beside the implementation once and replace every body; the generator never touches it afterwards.

pub mod abi {
    include!(concat!(env!("API_GEN_RUST_DIR"), "/xy_api_abi.rs"));
}

use abi::{Offset, Stats, Status, Wrap, ffi};

pub fn open_port(
    unit: u32,
    pport: Option<&mut ffi::xy_port>,
    pstats: Option<&mut Stats>,
    generation: Option<&mut u32>,
    pwrap: Option<&mut Wrap>,
) -> Result<(), Status> {
    let _ = unit;
    let _ = pport;
    let _ = pstats;
    let _ = generation;
    let _ = pwrap;
    // replace: not implemented
    Ok(())
}

/// release the port
pub fn destroy_port(hport: ffi::xy_port) -> Result<(), Status> {
    let _ = hport;
    // replace: not implemented
    Ok(())
}

/// buf: bytes to send
pub fn send(hport: ffi::xy_port, buf: Option<&[u8]>) -> Result<(), Status> {
    let _ = hport;
    let _ = buf;
    // replace: not implemented
    Ok(())
}

pub fn spend(htoken: ffi::xy_token) -> Result<(), Status> {
    let _ = htoken;
    // replace: not implemented
    Ok(())
}

pub fn recv(hport: ffi::xy_port, pdst: Option<&mut [u8]>) -> Result<(), Status> {
    let _ = hport;
    let _ = pdst;
    // replace: not implemented
    Ok(())
}

pub fn configure(
    hport: ffi::xy_port,
    cfg: Option<&Stats>,
    limit: Option<&u32>,
    mode: ffi::xy_mode,
    who: ffi::xy_token,
) -> Result<(), Status> {
    let _ = hport;
    let _ = cfg;
    let _ = limit;
    let _ = mode;
    let _ = who;
    // replace: not implemented
    Ok(())
}

pub fn stats_of(
    hport: ffi::xy_port,
    out: Option<&mut Stats>,
    pcount: Option<&mut u32>,
    plink: Option<&mut ffi::xy_link>,
) -> Result<(), Status> {
    let _ = hport;
    let _ = out;
    let _ = pcount;
    let _ = plink;
    // replace: not implemented
    Ok(())
}

/// level + 1, tally.count * 2, each byte of data + 1
pub fn bump(
    hport: ffi::xy_port,
    level: Option<&mut u32>,
    tally: Option<&mut Stats>,
    data: Option<&mut [u8]>,
) -> Result<(), Status> {
    let _ = hport;
    let _ = level;
    let _ = tally;
    let _ = data;
    // replace: not implemented
    Ok(())
}

pub fn open_link(plink: Option<&mut ffi::xy_link>) -> Result<(), Status> {
    let _ = plink;
    // replace: not implemented
    Ok(())
}

/// ok iff note is absent or note.count == 7
pub fn annotate(hport: ffi::xy_port, note: Option<&Stats>) -> Result<(), Status> {
    let _ = hport;
    let _ = note;
    // replace: not implemented
    Ok(())
}

pub fn reset() -> Result<(), Status> {
    // replace: not implemented
    Ok(())
}

pub fn seek(hport: ffi::xy_port, offset: u64) -> Result<(), Status> {
    let _ = hport;
    let _ = offset;
    // replace: not implemented
    Ok(())
}

/// pnext = big - 1, pdelta = delta - 1; ok iff delta == -3, big == -(1 << 40), small == 200, scale == 0.5
pub fn tune(
    hport: ffi::xy_port,
    delta: i32,
    big: i64,
    small: u8,
    scale: f64,
    pnext: Option<&mut i64>,
    pdelta: Option<&mut i32>,
) -> Result<(), Status> {
    let _ = hport;
    let _ = delta;
    let _ = big;
    let _ = small;
    let _ = scale;
    let _ = pnext;
    let _ = pdelta;
    // replace: not implemented
    Ok(())
}

/// pmode = slow, level + 1 and ppeek = 9 where given; ok iff payload is absent or 2 bytes and limit is absent or 3
pub fn probe(
    hport: ffi::xy_port,
    pmode: Option<&mut ffi::xy_mode>,
    payload: Option<&[u8]>,
    limit: Option<&u32>,
    level: Option<&mut u32>,
    ppeek: Option<&mut u32>,
) -> Result<(), Status> {
    let _ = hport;
    let _ = pmode;
    let _ = payload;
    let _ = limit;
    let _ = level;
    let _ = ppeek;
    // replace: not implemented
    Ok(())
}

/// ppos = pos
pub fn echo_offset(
    hport: ffi::xy_port,
    pos: Offset,
    ppos: Option<&mut Offset>,
) -> Result<(), Status> {
    let _ = hport;
    let _ = pos;
    let _ = ppos;
    // replace: not implemented
    Ok(())
}
