// GENERATED by vdev/api_gen from xy_api.adef.toml; do not edit.

pub mod ffi {
    #![allow(non_camel_case_types)]

    pub const XY_API_VERSION: u32 = 0x01020304;

    // feature flags
    pub const XY_FEAT_A: i32 = 1 << 0;
    /// the b feature
    pub const XY_FEAT_B: i32 = 1 << 3;
    pub const XY_FEAT_AB: i32 = XY_FEAT_A | XY_FEAT_B;
    pub const XY_FEAT_LIT: i32 = XY_FEAT_A | 4;

    pub const XY_FEAT_ONE: u32 = 1 << 0;
    pub const XY_FEAT_ALL: u32 = XY_FEAT_ONE | 8;

    // access flags
    pub const XY_ACC_A: i32 = 1 << 0;
    pub const XY_ACC_B: i32 = 1 << 1;
    pub const XY_ACC_AB: i32 = XY_ACC_A | XY_ACC_B;

    // limits
    pub const XY_MAX_UNITS: i32 = 16;
    pub const XY_EXTRA: i32 = 4;
    pub const XY_MAX_TOTAL: i32 = XY_MAX_UNITS + XY_EXTRA;
    pub const XY_NEG: i32 = -0x5;
    pub const XY_LOW: i32 = -7;
    pub const XY_FLOOR: i32 = -0x80000000;
    pub const XY_DIP: i32 = XY_MAX_UNITS + -3;

    // wire values
    /// wire magic
    pub const XY_MAGIC: u32 = 0xbeef;

    /// call outcome
    pub type xy_status = i32;
    pub const XY_OK: xy_status = 0;
    /// try later
    pub const XY_ERR_BUSY: xy_status = 9;
    pub const XY_ERR_OTHER: xy_status = 0x7fffffff;
    pub const XY_ERR_AGAIN: xy_status = 10;
    pub const XY_ERR_UNSUPPORTED: xy_status = 12;
    pub const XY_ERR_FLOOR: xy_status = -0x80000000;

    pub type xy_mode = u32;
    pub const XY_FINE: xy_mode = 0;
    pub const XY_SLOW: xy_mode = 1;

    pub const XY_PRODUCT: &str = "xy widget";
    /// who made it
    pub const XY_VENDOR: &str = "acme";

    /// a port
    pub type xy_port = *mut xy_port_opaque;
    #[repr(C)]
    pub struct xy_port_opaque {
        _private: [u8; 0],
    }

    pub type xy_token = *mut xy_token_opaque;
    #[repr(C)]
    pub struct xy_token_opaque {
        _private: [u8; 0],
    }

    pub type xy_link = *mut xy_link_opaque;
    #[repr(C)]
    pub struct xy_link_opaque {
        _private: [u8; 0],
    }

    /// a device offset
    #[repr(transparent)]
    #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct xy_offset(pub u64);

    /// counters
    #[repr(C)]
    #[derive(Clone, Copy, Debug, Default, PartialEq)]
    pub struct xy_stats {
        /// items seen
        pub count: u32,
        pub bytes: u64,
    }

    #[repr(C)]
    #[derive(Clone, Copy, Debug, Default, PartialEq)]
    pub struct xy_wrap {
        pub inner: xy_stats,
        pub n: u32,
    }
}

/// call outcome
#[repr(i32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    Ok = 0,
    /// try later
    ErrBusy = 9,
    ErrOther = 0x7fffffff,
    ErrAgain = 10,
    ErrUnsupported = 12,
    ErrFloor = -0x80000000,
}

impl core::convert::TryFrom<i32> for Status {
    type Error = i32;

    fn try_from(raw: i32) -> core::result::Result<Status, i32> {
        match raw {
            0 => Ok(Status::Ok),
            9 => Ok(Status::ErrBusy),
            0x7fffffff => Ok(Status::ErrOther),
            10 => Ok(Status::ErrAgain),
            12 => Ok(Status::ErrUnsupported),
            -0x80000000 => Ok(Status::ErrFloor),
            _ => Err(raw),
        }
    }
}

impl Status {
    pub fn to_string(self) -> &'static str {
        match self {
            Status::Ok => "OK",
            Status::ErrBusy => "ERR_BUSY",
            Status::ErrOther => "ERR_OTHER",
            Status::ErrAgain => "ERR_AGAIN",
            Status::ErrUnsupported => "ERR_UNSUPPORTED",
            Status::ErrFloor => "ERR_FLOOR",
        }
    }
}

impl core::fmt::Display for Status {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(Status::to_string(*self))
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Mode {
    Fine = 0,
    Slow = 1,
}

impl core::convert::TryFrom<u32> for Mode {
    type Error = u32;

    fn try_from(raw: u32) -> core::result::Result<Mode, u32> {
        match raw {
            0 => Ok(Mode::Fine),
            1 => Ok(Mode::Slow),
            _ => Err(raw),
        }
    }
}

impl Mode {
    pub fn to_string(self) -> &'static str {
        match self {
            Mode::Fine => "FINE",
            Mode::Slow => "SLOW",
        }
    }
}

impl core::fmt::Display for Mode {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(Mode::to_string(*self))
    }
}

pub use ffi::xy_offset as Offset;
pub use ffi::xy_stats as Stats;
pub use ffi::xy_wrap as Wrap;

/// A C byte count as a slice length: `None` below zero or above `isize::MAX`.
fn c_len(count: impl core::convert::TryInto<isize>) -> Option<usize> {
    usize::try_from(count.try_into().ok()?).ok()
}

/// A C `in` buffer as the implementation's slice: `None` for a null pointer or a count above
/// `isize::MAX`.
///
/// # Safety
///
/// A non-null `ptr` is valid for reads of `count` bytes while the slice lives.
unsafe fn c_bytes<'a>(
    ptr: *const core::ffi::c_void,
    count: impl core::convert::TryInto<isize>,
) -> Option<&'a [u8]> {
    let len = c_len(count)?;
    if ptr.is_null() {
        return None;
    }
    Some(unsafe { core::slice::from_raw_parts(ptr.cast(), len) })
}

/// A C `inout` buffer as the implementation's slice: `None` for a null pointer or a count above
/// `isize::MAX`.
///
/// # Safety
///
/// A non-null `ptr` is valid for reads and writes of `count` initialised bytes while the slice
/// lives.
unsafe fn c_bytes_mut<'a>(
    ptr: *mut core::ffi::c_void,
    count: impl core::convert::TryInto<isize>,
) -> Option<&'a mut [u8]> {
    let len = c_len(count)?;
    if ptr.is_null() {
        return None;
    }
    Some(unsafe { core::slice::from_raw_parts_mut(ptr.cast(), len) })
}

/// A C `out` buffer as the implementation's slice, zero-filled first, since the caller's memory
/// may be uninitialised: `None` for a null pointer or a count above `isize::MAX`.
///
/// # Safety
///
/// A non-null `ptr` is valid for writes of `count` bytes while the slice lives.
unsafe fn c_bytes_zeroed<'a>(
    ptr: *mut core::ffi::c_void,
    count: impl core::convert::TryInto<isize>,
) -> Option<&'a mut [u8]> {
    let len = c_len(count)?;
    if ptr.is_null() {
        return None;
    }
    let ptr = ptr.cast::<u8>();
    unsafe { ptr.write_bytes(0, len) };
    Some(unsafe { core::slice::from_raw_parts_mut(ptr, len) })
}

/// pstats: may be null
///
/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_open_port(
    unit: u32,
    pport: *mut ffi::xy_port,
    pstats: *mut ffi::xy_stats,
    generation: *mut u32,
    pwrap: *mut ffi::xy_wrap,
) -> ffi::xy_status {
    let mut pport_local = (!pport.is_null()).then(core::ptr::null_mut);
    let mut pstats_local = (!pstats.is_null()).then(Stats::default);
    let mut generation_local = (!generation.is_null()).then(u32::default);
    let mut pwrap_local = (!pwrap.is_null()).then(Wrap::default);
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(
        u32,
        Option<&mut ffi::xy_port>,
        Option<&mut Stats>,
        Option<&mut u32>,
        Option<&mut Wrap>,
    ) -> Result<(), Status> = crate::open_port;
    let result = IMPLEMENTATION(
        unit,
        pport_local.as_mut(),
        pstats_local.as_mut(),
        generation_local.as_mut(),
        pwrap_local.as_mut(),
    );
    if let Some(pport_local) = pport_local {
        unsafe { pport.write(pport_local) };
    }
    if let Some(pstats_local) = pstats_local {
        unsafe { pstats.write(pstats_local) };
    }
    if let Some(generation_local) = generation_local {
        unsafe { generation.write(generation_local) };
    }
    if let Some(pwrap_local) = pwrap_local {
        unsafe { pwrap.write(pwrap_local) };
    }
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// release the port
///
/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_destroy_port(hport: ffi::xy_port) -> ffi::xy_status {
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(ffi::xy_port) -> Result<(), Status> = crate::destroy_port;
    let result = IMPLEMENTATION(hport);
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// buf: bytes to send
///
/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_send(
    hport: ffi::xy_port,
    buf: *const core::ffi::c_void,
    buf_count: u64,
) -> ffi::xy_status {
    let buf_local = unsafe { self::c_bytes(buf, buf_count) };
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(ffi::xy_port, Option<&[u8]>) -> Result<(), Status> = crate::send;
    let result = IMPLEMENTATION(hport, buf_local);
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_spend(htoken: ffi::xy_token) -> ffi::xy_status {
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(ffi::xy_token) -> Result<(), Status> = crate::spend;
    let result = IMPLEMENTATION(htoken);
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_recv(
    hport: ffi::xy_port,
    pdst: *mut core::ffi::c_void,
    pdst_count: u32,
) -> ffi::xy_status {
    let pdst_local = unsafe { self::c_bytes_zeroed(pdst, pdst_count) };
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(ffi::xy_port, Option<&mut [u8]>) -> Result<(), Status> = crate::recv;
    let result = IMPLEMENTATION(hport, pdst_local);
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_configure(
    hport: ffi::xy_port,
    cfg: *const ffi::xy_stats,
    limit: *const u32,
    mode: ffi::xy_mode,
    who: ffi::xy_token,
) -> ffi::xy_status {
    let cfg_local = (!cfg.is_null()).then(|| unsafe { cfg.read() });
    let limit_local = (!limit.is_null()).then(|| unsafe { limit.read() });
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(
        ffi::xy_port,
        Option<&Stats>,
        Option<&u32>,
        ffi::xy_mode,
        ffi::xy_token,
    ) -> Result<(), Status> = crate::configure;
    let result = IMPLEMENTATION(hport, cfg_local.as_ref(), limit_local.as_ref(), mode, who);
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_stats_of(
    hport: ffi::xy_port,
    out: *mut ffi::xy_stats,
    pcount: *mut u32,
    plink: *mut ffi::xy_link,
) -> ffi::xy_status {
    let mut out_local = (!out.is_null()).then(Stats::default);
    let mut pcount_local = (!pcount.is_null()).then(u32::default);
    let mut plink_local = (!plink.is_null()).then(core::ptr::null_mut);
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(
        ffi::xy_port,
        Option<&mut Stats>,
        Option<&mut u32>,
        Option<&mut ffi::xy_link>,
    ) -> Result<(), Status> = crate::stats_of;
    let result = IMPLEMENTATION(
        hport,
        out_local.as_mut(),
        pcount_local.as_mut(),
        plink_local.as_mut(),
    );
    if let Some(out_local) = out_local {
        unsafe { out.write(out_local) };
    }
    if let Some(pcount_local) = pcount_local {
        unsafe { pcount.write(pcount_local) };
    }
    if let Some(plink_local) = plink_local {
        unsafe { plink.write(plink_local) };
    }
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// level + 1, tally.count * 2, each byte of data + 1
///
/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_bump(
    hport: ffi::xy_port,
    level: *mut u32,
    tally: *mut ffi::xy_stats,
    data: *mut core::ffi::c_void,
    data_count: u32,
) -> ffi::xy_status {
    let mut level_local = (!level.is_null()).then(|| unsafe { level.read() });
    let mut tally_local = (!tally.is_null()).then(|| unsafe { tally.read() });
    let data_local = unsafe { self::c_bytes_mut(data, data_count) };
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(
        ffi::xy_port,
        Option<&mut u32>,
        Option<&mut Stats>,
        Option<&mut [u8]>,
    ) -> Result<(), Status> = crate::bump;
    let result = IMPLEMENTATION(
        hport,
        level_local.as_mut(),
        tally_local.as_mut(),
        data_local,
    );
    if let Some(level_local) = level_local {
        unsafe { level.write(level_local) };
    }
    if let Some(tally_local) = tally_local {
        unsafe { tally.write(tally_local) };
    }
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_open_link(plink: *mut ffi::xy_link) -> ffi::xy_status {
    let mut plink_local = (!plink.is_null()).then(core::ptr::null_mut);
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(Option<&mut ffi::xy_link>) -> Result<(), Status> = crate::open_link;
    let result = IMPLEMENTATION(plink_local.as_mut());
    if let Some(plink_local) = plink_local {
        unsafe { plink.write(plink_local) };
    }
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// ok iff note is absent or note.count == 7
///
/// note: may be null
///
/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_annotate(
    hport: ffi::xy_port,
    note: *const ffi::xy_stats,
) -> ffi::xy_status {
    let note_local = (!note.is_null()).then(|| unsafe { note.read() });
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(ffi::xy_port, Option<&Stats>) -> Result<(), Status> = crate::annotate;
    let result = IMPLEMENTATION(hport, note_local.as_ref());
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_reset() -> ffi::xy_status {
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn() -> Result<(), Status> = crate::reset;
    let result = IMPLEMENTATION();
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_seek(hport: ffi::xy_port, offset: u64) -> ffi::xy_status {
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(ffi::xy_port, u64) -> Result<(), Status> = crate::seek;
    let result = IMPLEMENTATION(hport, offset);
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// pnext = big - 1, pdelta = delta - 1; ok iff delta == -3, big == -(1 << 40), small == 200, scale == 0.5
///
/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_tune(
    hport: ffi::xy_port,
    delta: i32,
    big: i64,
    small: u8,
    scale: f64,
    pnext: *mut i64,
    pdelta: *mut i32,
) -> ffi::xy_status {
    let mut pnext_local = (!pnext.is_null()).then(i64::default);
    let mut pdelta_local = (!pdelta.is_null()).then(i32::default);
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(
        ffi::xy_port,
        i32,
        i64,
        u8,
        f64,
        Option<&mut i64>,
        Option<&mut i32>,
    ) -> Result<(), Status> = crate::tune;
    let result = IMPLEMENTATION(
        hport,
        delta,
        big,
        small,
        scale,
        pnext_local.as_mut(),
        pdelta_local.as_mut(),
    );
    if let Some(pnext_local) = pnext_local {
        unsafe { pnext.write(pnext_local) };
    }
    if let Some(pdelta_local) = pdelta_local {
        unsafe { pdelta.write(pdelta_local) };
    }
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// pmode = slow, level + 1 and ppeek = 9 where given; ok iff payload is absent or 2 bytes and limit is absent or 3
///
/// payload: may be null
/// limit: may be null
/// level: may be null
/// ppeek: may be null
///
/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_probe(
    hport: ffi::xy_port,
    pmode: *mut ffi::xy_mode,
    payload: *const core::ffi::c_void,
    payload_count: u32,
    limit: *const u32,
    level: *mut u32,
    ppeek: *mut u32,
) -> ffi::xy_status {
    let mut pmode_local = (!pmode.is_null()).then(ffi::xy_mode::default);
    let payload_local = unsafe { self::c_bytes(payload, payload_count) };
    let limit_local = (!limit.is_null()).then(|| unsafe { limit.read() });
    let mut level_local = (!level.is_null()).then(|| unsafe { level.read() });
    let mut ppeek_local = (!ppeek.is_null()).then(u32::default);
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(
        ffi::xy_port,
        Option<&mut ffi::xy_mode>,
        Option<&[u8]>,
        Option<&u32>,
        Option<&mut u32>,
        Option<&mut u32>,
    ) -> Result<(), Status> = crate::probe;
    let result = IMPLEMENTATION(
        hport,
        pmode_local.as_mut(),
        payload_local,
        limit_local.as_ref(),
        level_local.as_mut(),
        ppeek_local.as_mut(),
    );
    if let Some(pmode_local) = pmode_local {
        unsafe { pmode.write(pmode_local) };
    }
    if let Some(level_local) = level_local {
        unsafe { level.write(level_local) };
    }
    if let Some(ppeek_local) = ppeek_local {
        unsafe { ppeek.write(ppeek_local) };
    }
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

/// ppos = pos
///
/// # Safety
///
/// Every pointer argument must be null or valid for the call as the C header declares it, no buffer may overlap another argument of the same call, and no other thread may read or write a buffer argument during the call. A panic in the implementation aborts the process.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xy_echo_offset(
    hport: ffi::xy_port,
    pos: ffi::xy_offset,
    ppos: *mut ffi::xy_offset,
) -> ffi::xy_status {
    let mut ppos_local = (!ppos.is_null()).then(Offset::default);
    #[allow(clippy::type_complexity)]
    const IMPLEMENTATION: fn(ffi::xy_port, Offset, Option<&mut Offset>) -> Result<(), Status> =
        crate::echo_offset;
    let result = IMPLEMENTATION(hport, pos, ppos_local.as_mut());
    if let Some(ppos_local) = ppos_local {
        unsafe { ppos.write(ppos_local) };
    }
    match result {
        Ok(()) => ffi::XY_OK,
        Err(e) => e as ffi::xy_status,
    }
}

// Pins to the wrapped API: the implementation build fails if a pinned constant disagrees with its header
pub mod wrapped_api {
    #![allow(
        dead_code,
        non_camel_case_types,
        non_snake_case,
        non_upper_case_globals
    )]
    include!(concat!(env!("OUT_DIR"), "/wrapped_api.rs"));
}

const _: () = assert!(
    ffi::XY_FEAT_A as i64 == wrapped_api::XYD_FEAT_A as i64,
    "XY_FEAT_A must match XYD_FEAT_A"
);
