// GENERATED by vdev/api_gen from xy_api.adef.toml; do not edit.

pub mod ffi {
    #![allow(non_camel_case_types)]

    /// call outcome
    pub type xy_status = i32;

    pub type xy_mode = u32;

    /// a port
    pub type xy_port = *mut xy_port_opaque;
    #[repr(C)]
    pub struct xy_port_opaque {
        _private: [u8; 0],
    }

    pub type xy_token = *mut xy_token_opaque;
    #[repr(C)]
    pub struct xy_token_opaque {
        _private: [u8; 0],
    }

    pub type xy_link = *mut xy_link_opaque;
    #[repr(C)]
    pub struct xy_link_opaque {
        _private: [u8; 0],
    }

    /// a device offset
    #[repr(transparent)]
    #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct xy_offset(pub u64);

    /// counters
    #[repr(C)]
    #[derive(Clone, Copy, Debug, Default, PartialEq)]
    pub struct xy_stats {
        /// items seen
        pub count: u32,
        pub bytes: u64,
    }

    #[repr(C)]
    #[derive(Clone, Copy, Debug, Default, PartialEq)]
    pub struct xy_wrap {
        pub inner: xy_stats,
        pub n: u32,
    }

    #[link(name = "xy")]
    unsafe extern "C" {
        pub fn xy_open_port(
            unit: u32,
            pport: *mut xy_port,
            pstats: *mut xy_stats,
            generation: *mut u32,
            pwrap: *mut xy_wrap,
        ) -> xy_status;

        /// release the port
        pub fn xy_destroy_port(hport: xy_port) -> xy_status;

        /// buf: bytes to send
        pub fn xy_send(hport: xy_port, buf: *const core::ffi::c_void, buf_count: u64) -> xy_status;

        pub fn xy_spend(htoken: xy_token) -> xy_status;

        pub fn xy_recv(hport: xy_port, pdst: *mut core::ffi::c_void, pdst_count: u32) -> xy_status;

        pub fn xy_configure(
            hport: xy_port,
            cfg: *const xy_stats,
            limit: *const u32,
            mode: xy_mode,
            who: xy_token,
        ) -> xy_status;

        pub fn xy_stats_of(
            hport: xy_port,
            out: *mut xy_stats,
            pcount: *mut u32,
            plink: *mut xy_link,
        ) -> xy_status;

        /// level + 1, tally.count * 2, each byte of data + 1
        pub fn xy_bump(
            hport: xy_port,
            level: *mut u32,
            tally: *mut xy_stats,
            data: *mut core::ffi::c_void,
            data_count: u32,
        ) -> xy_status;

        pub fn xy_open_link(plink: *mut xy_link) -> xy_status;

        /// ok iff note is absent or note.count == 7
        pub fn xy_annotate(hport: xy_port, note: *const xy_stats) -> xy_status;

        pub fn xy_reset() -> xy_status;

        pub fn xy_seek(hport: xy_port, offset: u64) -> xy_status;

        /// pnext = big - 1, pdelta = delta - 1; ok iff delta == -3, big == -(1 << 40), small == 200, scale == 0.5
        pub fn xy_tune(
            hport: xy_port,
            delta: i32,
            big: i64,
            small: u8,
            scale: f64,
            pnext: *mut i64,
            pdelta: *mut i32,
        ) -> xy_status;

        /// pmode = slow, level + 1 and ppeek = 9 where given; ok iff payload is absent or 2 bytes and limit is absent or 3
        pub fn xy_probe(
            hport: xy_port,
            pmode: *mut xy_mode,
            payload: *const core::ffi::c_void,
            payload_count: u32,
            limit: *const u32,
            level: *mut u32,
            ppeek: *mut u32,
        ) -> xy_status;

        /// ppos = pos
        pub fn xy_echo_offset(hport: xy_port, pos: xy_offset, ppos: *mut xy_offset) -> xy_status;
    }
}

pub const API_VERSION: u32 = 0x01020304;

// feature flags
pub const FEAT_A: i32 = 1 << 0;
/// the b feature
pub const FEAT_B: i32 = 1 << 3;
pub const FEAT_AB: i32 = FEAT_A | FEAT_B;
pub const FEAT_LIT: i32 = FEAT_A | 4;

pub const FEAT_ONE: u32 = 1 << 0;
pub const FEAT_ALL: u32 = FEAT_ONE | 8;

// access flags
pub const ACC_A: i32 = 1 << 0;
pub const ACC_B: i32 = 1 << 1;
pub const ACC_AB: i32 = ACC_A | ACC_B;

pub fn access_to_string(mut value: i32) -> String {
    if value == 0 {
        return String::from("NONE");
    }
    let mut text = String::new();
    if value & ACC_A != 0 {
        text += "|ACC_A";
        value &= !ACC_A;
    }
    if value & ACC_B != 0 {
        text += "|ACC_B";
        value &= !ACC_B;
    }
    if value != 0 {
        text += &format!("|{value:#x}");
    }
    text[1..].to_string()
}

// limits
pub const MAX_UNITS: i32 = 16;
pub const EXTRA: i32 = 4;
pub const MAX_TOTAL: i32 = MAX_UNITS + EXTRA;
pub const NEG: i32 = -0x5;
pub const LOW: i32 = -7;
pub const FLOOR: i32 = -0x80000000;
pub const DIP: i32 = MAX_UNITS + -3;

pub fn limit_to_string(value: i32) -> &'static str {
    match value {
        MAX_UNITS => "MAX_UNITS",
        EXTRA => "EXTRA",
        MAX_TOTAL => "MAX_TOTAL",
        NEG => "NEG",
        LOW => "LOW",
        FLOOR => "FLOOR",
        DIP => "DIP",
        _ => "UNKNOWN",
    }
}

// wire values
/// wire magic
pub const MAGIC: u32 = 0xbeef;

pub const PRODUCT: &str = "xy widget";
/// who made it
pub const VENDOR: &str = "acme";

/// call outcome
#[repr(i32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    Ok = 0,
    /// try later
    ErrBusy = 9,
    ErrOther = 0x7fffffff,
    ErrAgain = 10,
    ErrUnsupported = 12,
    ErrFloor = -0x80000000,
}

impl core::convert::TryFrom<i32> for Status {
    type Error = i32;

    fn try_from(raw: i32) -> core::result::Result<Status, i32> {
        match raw {
            0 => Ok(Status::Ok),
            9 => Ok(Status::ErrBusy),
            0x7fffffff => Ok(Status::ErrOther),
            10 => Ok(Status::ErrAgain),
            12 => Ok(Status::ErrUnsupported),
            -0x80000000 => Ok(Status::ErrFloor),
            _ => Err(raw),
        }
    }
}

impl Status {
    pub fn to_string(self) -> &'static str {
        match self {
            Status::Ok => "OK",
            Status::ErrBusy => "ERR_BUSY",
            Status::ErrOther => "ERR_OTHER",
            Status::ErrAgain => "ERR_AGAIN",
            Status::ErrUnsupported => "ERR_UNSUPPORTED",
            Status::ErrFloor => "ERR_FLOOR",
        }
    }
}

impl core::fmt::Display for Status {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(Status::to_string(*self))
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Mode {
    Fine = 0,
    Slow = 1,
}

impl core::convert::TryFrom<u32> for Mode {
    type Error = u32;

    fn try_from(raw: u32) -> core::result::Result<Mode, u32> {
        match raw {
            0 => Ok(Mode::Fine),
            1 => Ok(Mode::Slow),
            _ => Err(raw),
        }
    }
}

impl Mode {
    pub fn to_string(self) -> &'static str {
        match self {
            Mode::Fine => "FINE",
            Mode::Slow => "SLOW",
        }
    }
}

impl core::fmt::Display for Mode {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(Mode::to_string(*self))
    }
}

pub use ffi::xy_offset as Offset;
pub use ffi::xy_stats as Stats;
pub use ffi::xy_wrap as Wrap;

/// a port
pub struct Port {
    handle: ffi::xy_port,
    pstats: Stats,
    generation: u32,
    pwrap: Wrap,
}

impl Port {
    pub fn create(unit: u32) -> Result<Port, Status> {
        let mut pport = core::ptr::null_mut();
        let mut pstats = Stats::default();
        let mut generation = u32::default();
        let mut pwrap = Wrap::default();
        // SAFETY: every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe {
            ffi::xy_open_port(unit, &mut pport, &mut pstats, &mut generation, &mut pwrap)
        };
        let result =
            Status::try_from(raw).expect("xy_open_port returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(Port {
            handle: pport,
            pstats,
            generation,
            pwrap,
        })
    }

    pub fn handle(&self) -> ffi::xy_port {
        self.handle
    }

    pub fn pstats(&self) -> &Stats {
        &self.pstats
    }

    pub fn generation(&self) -> u32 {
        self.generation
    }

    pub fn pwrap(&self) -> &Wrap {
        &self.pwrap
    }

    /// buf: bytes to send
    pub fn send(&self, buf: &[u8]) -> Result<(), Status> {
        let buf_count = u64::try_from(buf.len()).expect("buf is longer than u64 can count");
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe { ffi::xy_send(self.handle, buf.as_ptr().cast(), buf_count) };
        let result =
            Status::try_from(raw).expect("xy_send returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(())
    }

    pub fn recv(&self, pdst: &mut [u8]) -> Result<(), Status> {
        let pdst_count = u32::try_from(pdst.len()).expect("pdst is longer than u32 can count");
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe { ffi::xy_recv(self.handle, pdst.as_mut_ptr().cast(), pdst_count) };
        let result =
            Status::try_from(raw).expect("xy_recv returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(())
    }

    /// # Safety
    ///
    /// `who` must be a handle the library issued and has not yet destroyed.
    pub unsafe fn configure(
        &self,
        cfg: &Stats,
        limit: &u32,
        mode: Mode,
        who: ffi::xy_token,
    ) -> Result<(), Status> {
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe { ffi::xy_configure(self.handle, cfg, limit, mode as ffi::xy_mode, who) };
        let result =
            Status::try_from(raw).expect("xy_configure returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(())
    }

    pub fn stats_of(&self) -> Result<(Stats, u32, ffi::xy_link), Status> {
        let mut out = Stats::default();
        let mut pcount = u32::default();
        let mut plink = core::ptr::null_mut();
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe { ffi::xy_stats_of(self.handle, &mut out, &mut pcount, &mut plink) };
        let result =
            Status::try_from(raw).expect("xy_stats_of returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok((out, pcount, plink))
    }

    /// level + 1, tally.count * 2, each byte of data + 1
    pub fn bump(&self, level: &mut u32, tally: &mut Stats, data: &mut [u8]) -> Result<(), Status> {
        let data_count = u32::try_from(data.len()).expect("data is longer than u32 can count");
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe {
            ffi::xy_bump(
                self.handle,
                level,
                tally,
                data.as_mut_ptr().cast(),
                data_count,
            )
        };
        let result =
            Status::try_from(raw).expect("xy_bump returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(())
    }

    /// ok iff note is absent or note.count == 7
    pub fn annotate(&self, note: Option<&Stats>) -> Result<(), Status> {
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe {
            ffi::xy_annotate(
                self.handle,
                note.map_or(core::ptr::null(), core::ptr::from_ref),
            )
        };
        let result =
            Status::try_from(raw).expect("xy_annotate returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(())
    }

    pub fn seek(&self, offset: u64) -> Result<(), Status> {
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe { ffi::xy_seek(self.handle, offset) };
        let result =
            Status::try_from(raw).expect("xy_seek returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(())
    }

    /// pnext = big - 1, pdelta = delta - 1; ok iff delta == -3, big == -(1 << 40), small == 200, scale == 0.5
    pub fn tune(&self, delta: i32, big: i64, small: u8, scale: f64) -> Result<(i64, i32), Status> {
        let mut pnext = i64::default();
        let mut pdelta = i32::default();
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe {
            ffi::xy_tune(
                self.handle,
                delta,
                big,
                small,
                scale,
                &mut pnext,
                &mut pdelta,
            )
        };
        let result =
            Status::try_from(raw).expect("xy_tune returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok((pnext, pdelta))
    }

    /// pmode = slow, level + 1 and ppeek = 9 where given; ok iff payload is absent or 2 bytes and limit is absent or 3
    pub fn probe(
        &self,
        payload: Option<&[u8]>,
        limit: Option<&u32>,
        level: Option<&mut u32>,
        ppeek: Option<&mut u32>,
    ) -> Result<Mode, Status> {
        let mut pmode = ffi::xy_mode::default();
        let payload_count = u32::try_from(payload.map_or(0, <[u8]>::len))
            .expect("payload is longer than u32 can count");
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe {
            ffi::xy_probe(
                self.handle,
                &mut pmode,
                payload.map_or(core::ptr::null(), <[u8]>::as_ptr).cast(),
                payload_count,
                limit.map_or(core::ptr::null(), core::ptr::from_ref),
                level.map_or(core::ptr::null_mut(), core::ptr::from_mut),
                ppeek.map_or(core::ptr::null_mut(), core::ptr::from_mut),
            )
        };
        let result =
            Status::try_from(raw).expect("xy_probe returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        let pmode =
            Mode::try_from(pmode).expect("xy_probe wrote a pmode value xy_mode does not name");
        Ok(pmode)
    }

    /// ppos = pos
    pub fn echo_offset(&self, pos: Offset) -> Result<Offset, Status> {
        let mut ppos = Offset::default();
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe { ffi::xy_echo_offset(self.handle, pos, &mut ppos) };
        let result =
            Status::try_from(raw).expect("xy_echo_offset returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(ppos)
    }

    /// release the port
    pub fn release(self) -> Result<(), Status> {
        let handle = self.handle;
        core::mem::forget(self);
        // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe { ffi::xy_destroy_port(handle) };
        let result = Status::try_from(raw)
            .expect("xy_destroy_port returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(())
    }
}

impl Drop for Port {
    fn drop(&mut self) {
        if !self.handle.is_null() {
            // SAFETY: the handle came from a successful create and is not yet released; every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
            let _ = unsafe { ffi::xy_destroy_port(self.handle) };
        }
    }
}

pub struct DataLink {
    handle: ffi::xy_link,
}

impl DataLink {
    pub fn create() -> Result<DataLink, Status> {
        let mut plink = core::ptr::null_mut();
        // SAFETY: every pointer argument points at a local or a caller reference that lives for the call, a slice's length its count; the library keeps no pointer after returning.
        let raw = unsafe { ffi::xy_open_link(&mut plink) };
        let result =
            Status::try_from(raw).expect("xy_open_link returned a value xy_status does not name");
        if result != Status::Ok {
            return Err(result);
        }
        Ok(DataLink { handle: plink })
    }

    pub fn handle(&self) -> ffi::xy_link {
        self.handle
    }
}
