import contextlib
import io
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from api_gen import __main__ as api_gen_main
from api_gen import emit_c, emit_cpp_stub, model
from api_gen.tests.test_api_gen import FIXTURE, load

STATUS_ERRORS = 'err_busy = { value = 9, docstring = "try later" }\nerr_other = { value = 0x7fffffff, format = "hex" }\n'


def stub(text: str = FIXTURE) -> str:
    return emit_cpp_stub.stub(load(text), source_name="xy_api.adef.toml", stem="xy_api")


def param_lists(text: str, pattern: str) -> dict[str, str]:
    """Function name -> parameter list text, for every `<pattern>xy_<f>(<params>)` in text."""
    return dict(re.findall(pattern + r"xy_(\w+)\(([^)]*)\)", text))


class Stub(unittest.TestCase):
    def setUp(self) -> None:
        self.text = stub()

    def test_banner(self) -> None:
        self.assertEqual(
            self.text.splitlines()[0],
            "// GENERATED by vdev/api_gen from xy_api.adef.toml: implementation stub. "
            "Copy into lib/ once and replace every body; the generator never touches lib/.",
        )

    def test_impl_define_include_undef_then_std_includes(self) -> None:
        self.assertIn(
            '#define XY_IMPL\n#include "xy_api.h"\n#undef XY_IMPL\n\n'
            "#include <cerrno>\n#include <cstdint>\n#include <cstring>\n",
            self.text,
        )

    def test_signatures_match_the_header_in_document_order(self) -> None:
        header = param_lists(emit_c.header(load(), source_name="x"), r"XY_API xy_status ")
        definitions = param_lists(self.text, r"XY_API xy_status ")
        self.assertEqual(list(definitions), ["open_port", "destroy_port", "send", "spend"])
        self.assertEqual(definitions, header)

    def test_every_parameter_voided(self) -> None:
        self.assertIn(
            "XY_API xy_status xy_send(xy_port hport, const void* buf, uint64_t len) {\n"
            "  (void)hport;\n  (void)buf;\n  (void)len;\n"
            "  // replace: not implemented\n",
            self.text,
        )

    def test_no_parameters(self) -> None:
        text = stub(FIXTURE + '\n[function.reset]\nreturn = "status"\n')
        self.assertIn("XY_API xy_status xy_reset(void) {\n  // replace: not implemented\n", text)

    def test_failure_is_first_nonzero_entry(self) -> None:
        self.assertEqual(self.text.count("  return XY_ERR_BUSY;\n}\n"), 4)

    def test_failure_prefers_err_unsupported(self) -> None:
        text = stub(FIXTURE.replace(STATUS_ERRORS, STATUS_ERRORS + "err_unsupported = 12\n"))
        self.assertEqual(text.count("  return XY_ERR_UNSUPPORTED;\n}\n"), 4)

    def test_no_nonzero_entry_is_an_error(self) -> None:
        with self.assertRaises(model.DefinitionError) as caught:
            stub(FIXTURE.replace(STATUS_ERRORS, ""))
        self.assertIn("cannot pick a failure result for the stub", str(caught.exception))


class Outputs(unittest.TestCase):
    def test_gendeps_lists_the_stub(self) -> None:
        argv = ["api_gen", "gendeps", "--generated", "OUT", "--exercise", "ex", "xy_api.adef.toml"]
        stdout = io.StringIO()
        with mock.patch.object(sys, "argv", argv), contextlib.redirect_stdout(stdout):
            self.assertEqual(api_gen_main.main(), 0)
        generated, rule = stdout.getvalue().splitlines()[1:3]
        self.assertTrue(generated.startswith("GENERATED += ") and generated.endswith(" OUT/stub/xy_api.cpp"))
        self.assertIn(" OUT/stub/xy_api.cpp &: xy_api.adef.toml", rule)

    @unittest.skipUnless(shutil.which("clang++"), "clang++ not on PATH")
    def test_stub_compiles_against_its_header_with_pins_active(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            definition = root / "xy_api.adef.toml"
            definition.write_text(FIXTURE, encoding="utf-8")
            generated = root / "generated"
            argv = ["api_gen", str(definition), "--generated", str(generated), "--exercise", "xy"]
            with mock.patch.object(sys, "argv", argv), contextlib.redirect_stderr(io.StringIO()):
                self.assertEqual(api_gen_main.main(), 0)
            driver = root / "xy" / "driver" / "xy_ioctl.h"
            driver.parent.mkdir(parents=True)
            driver.write_text("#define XYD_FEAT_A 1\n", encoding="utf-8")
            compiled = subprocess.run(
                [
                    "clang++", "--std=c++20", "-fsyntax-only", "-Wall", "-Wextra", "-Werror",
                    f"-I{generated / 'include' / 'xy'}", f"-I{root}", str(generated / "stub" / "xy_api.cpp"),
                ],
                capture_output=True,
                text=True,
            )
            self.assertEqual(compiled.returncode, 0, compiled.stderr)


if __name__ == "__main__":
    unittest.main()
