import contextlib
import io
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from api_gen import __main__ as api_gen_main
from api_gen import emit_c, emit_cpp_wrapper, model
from api_gen.tests.test_api_gen import FIXTURE, load


def wrapper(text: str = FIXTURE) -> str:
    return emit_cpp_wrapper.wrapper(load(text), source_name="xy_api.adef.toml", stem="xy_api")


class Wrapper(unittest.TestCase):
    def setUp(self) -> None:
        self.text = wrapper()

    def test_prelude(self) -> None:
        self.assertTrue(
            self.text.startswith(
                "// GENERATED by vdev/api_gen from xy_api.adef.toml; do not edit.\n"
                '#pragma once\n\n#include "xy_api.h"\n\n'
                "#include <utility>\n\n"
                "namespace xy {\n"
            )
        )
        self.assertTrue(self.text.endswith("}  // namespace xy\n"))

    def test_includes_nothing_else(self) -> None:
        includes = [line for line in self.text.splitlines() if line.startswith("#include")]
        self.assertEqual(len(includes), 2)
        for absent in ("throw", "new ", "iostream", "malloc"):
            self.assertNotIn(absent, self.text)

    def test_constants_are_unprefixed(self) -> None:
        for line in (
            "inline constexpr uint32_t API_VERSION = XY_API_VERSION;\n",
            "inline constexpr uint32_t FEAT_A = XY_FEAT_A;\n",
            "inline constexpr uint32_t FEAT_AB = XY_FEAT_AB;\n",
            "inline constexpr uint32_t MAGIC = XY_MAGIC;\n",
            "inline constexpr const char* VENDOR = XY_VENDOR;\n",
        ):
            self.assertIn(line, self.text)

    def test_enum_class_over_the_c_values(self) -> None:
        self.assertIn(
            "enum class [[nodiscard]] Status : int32_t {\n"
            "  Ok = XY_OK,\n  ErrBusy = XY_ERR_BUSY,\n  ErrOther = XY_ERR_OTHER,\n};\n",
            self.text,
        )

    def test_to_string(self) -> None:
        self.assertIn('inline const char* to_string(Status value) {\n  switch (value) {\n    case Status::Ok: return "OK";\n', self.text)
        self.assertIn('    case Status::ErrBusy: return "ERR_BUSY";\n', self.text)
        self.assertIn('  }\n  return "UNKNOWN_STATUS";\n}\n', self.text)

    def test_to_string_duplicate_value_takes_the_later_name(self) -> None:
        text = wrapper(FIXTURE.replace("[opaque_ref.port]", "err_again = 9\n\n[opaque_ref.port]"))
        self.assertIn('    case Status::ErrAgain: return "ERR_AGAIN";\n', text)
        self.assertNotIn("case Status::ErrBusy", text)

    def test_struct_alias(self) -> None:
        self.assertIn("using Stats = xy_stats;\n", self.text)
        self.assertNotIn("struct Stats", self.text)

    def test_class_only_for_opaque_with_ctor(self) -> None:
        self.assertIn("class Port {\n", self.text)
        self.assertNotIn("class Token", self.text)
        self.assertNotIn("xy_spend", self.text)

    def test_create(self) -> None:
        self.assertIn(
            "  [[nodiscard]] static Port create(uint32_t unit, Status* result = nullptr) {\n"
            "    xy_port pport{};\n    Stats pstats{};\n    uint32_t generation{};\n"
            "    const Status status = Status(xy_open_port(unit, &pport, &pstats, &generation));\n"
            "    if (result) {\n      *result = status;\n    }\n"
            "    if (status != Status::Ok) {\n      return Port(nullptr, {}, {});\n    }\n"
            "    return Port(pport, pstats, generation);\n",
            self.text,
        )

    def test_create_status_local_avoids_parameter_names(self) -> None:
        text = wrapper(FIXTURE.replace('unit = "u32"', 'status = "u32"'))
        self.assertIn("const Status status_ = Status(xy_open_port(status, ", text)

    def test_cached_outrefs_are_private_with_const_accessors(self) -> None:
        self.assertIn(
            "  const Stats& pstats() const { return pstats_; }\n"
            "  uint32_t generation() const { return generation_; }\n",
            self.text,
        )
        self.assertIn("  Stats pstats_;\n  uint32_t generation_;\n  xy_port handle_;\n", self.text)

    def test_move_construction(self) -> None:
        self.assertIn("  Port(const Port&) = delete;\n  Port& operator=(const Port&) = delete;\n", self.text)
        self.assertIn(
            "  Port(Port&& other) noexcept\n"
            "      : pstats_(other.pstats_), generation_(other.generation_), handle_(std::exchange(other.handle_, nullptr)) {}\n",
            self.text,
        )

    def test_move_assignment_releases_the_current_handle_first(self) -> None:
        self.assertIn(
            "  Port& operator=(Port&& other) noexcept {\n"
            "    if (this != &other) {\n"
            "      if (handle_) {\n        (void)release();\n      }\n"
            "      handle_ = std::exchange(other.handle_, nullptr);\n"
            "      pstats_ = other.pstats_;\n"
            "      generation_ = other.generation_;\n"
            "    }\n    return *this;\n  }\n",
            self.text,
        )

    def test_move_assignment_without_a_dtor_does_not_call_release(self) -> None:
        text = wrapper(FIXTURE.replace('dtor = "destroy_port"\n', ""))
        self.assertIn(
            "  Port& operator=(Port&& other) noexcept {\n"
            "    if (this != &other) {\n"
            "      handle_ = std::exchange(other.handle_, nullptr);\n"
            "      pstats_ = other.pstats_;\n"
            "      generation_ = other.generation_;\n"
            "    }\n    return *this;\n  }\n",
            text,
        )
        self.assertNotIn("release()", text)

    def test_destructor_releases_a_live_handle(self) -> None:
        self.assertIn("  ~Port() {\n    if (handle_) {\n      (void)release();\n    }\n  }\n", self.text)
        self.assertIn(
            "  Status release() {\n    return Status(xy_destroy_port(std::exchange(handle_, nullptr)));\n  }\n",
            self.text,
        )

    def test_no_dtor_no_release(self) -> None:
        text = wrapper(FIXTURE.replace('dtor = "destroy_port"\n', ""))
        self.assertNotIn("~Port", text)
        self.assertNotIn("release()", text)
        self.assertIn("  Status destroy_port() {\n", text)

    def test_handle_and_bool(self) -> None:
        self.assertIn("  explicit operator bool() const { return handle_ != nullptr; }\n", self.text)
        self.assertIn("  xy_port handle() const { return handle_; }\n", self.text)

    def test_inref_memory_is_a_const_pointer_and_its_size_stays_in_the_signature(self) -> None:
        self.assertIn(
            "  // buf: bytes to send\n  Status send(const void* buf, uint64_t len) {\n"
            "    return Status(xy_send(handle_, buf, len));\n",
            self.text,
        )

    def test_method_parameter_mapping(self) -> None:
        text = wrapper(
            FIXTURE
            + '\n[function.recv]\nreturn = "status"\nhport = "port"\npdst = { type = "memory", outref = true, size = "n" }\nn = "u32"\n'
            + 'cfg = { type = "stats", inref = true }\nout = { type = "stats", outref = true }\ncount = { type = "u32", outref = true }\n'
            + 'mode = "status"\nwho = "token"\n'
        )
        self.assertIn(
            "  Status recv(void* pdst, uint32_t n, const Stats& cfg, Stats& out, uint32_t& count, Status mode, xy_token who) {\n"
            "    return Status(xy_recv(handle_, pdst, n, &cfg, &out, &count, xy_status(mode), who));\n",
            text,
        )

    def test_member_collision_is_an_error(self) -> None:
        with self.assertRaises(model.DefinitionError) as caught:
            wrapper(FIXTURE.replace("[function.send]", "[function.release]"))
        self.assertIn("C++ wrapper: class Port: release would be defined more than once", str(caught.exception))

    def test_ctor_memory_outref_is_an_error(self) -> None:
        text = FIXTURE.replace(
            'generation = { type = "u32", outref = true }',
            'generation = { type = "u32", outref = true }\nblob = { type = "memory", outref = true, size = "unit" }',
        )
        with self.assertRaises(model.DefinitionError) as caught:
            wrapper(text)
        self.assertIn("a constructor cannot cache a memory outref", str(caught.exception))

    def test_namespace_collision_is_an_error(self) -> None:
        with self.assertRaises(model.DefinitionError) as caught:
            wrapper(FIXTURE.replace("[untyped_const]\n", "[untyped_const]\nx = 1\n") + '\n[struct.x]\nv = "u32"\n')
        self.assertIn("C++ wrapper: namespace xy: X would be defined more than once", str(caught.exception))


class Outputs(unittest.TestCase):
    def generate(self, root: Path) -> Path:
        definition = root / "xy_api.adef.toml"
        definition.write_text(FIXTURE, encoding="utf-8")
        generated = root / "generated"
        argv = ["api_gen", str(definition), "--generated", str(generated), "--exercise", "xy"]
        with mock.patch.object(sys, "argv", argv), contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(api_gen_main.main(), 0)
        return generated

    def test_gendeps_lists_the_wrapper(self) -> None:
        argv = ["api_gen", "gendeps", "xy_api.adef.toml"]
        stdout = io.StringIO()
        with mock.patch.object(sys, "argv", argv), contextlib.redirect_stdout(stdout):
            self.assertEqual(api_gen_main.main(), 0)
        self.assertIn("  $(GEN)/include/$(BASE)/xy_api.hpp \\\n", stdout.getvalue())

    def test_generation_writes_the_wrapper_beside_the_header(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            include = self.generate(Path(tmp)) / "include" / "xy"
            self.assertEqual(sorted(p.name for p in include.iterdir()), ["xy_api.h", "xy_api.hpp"])
            self.assertEqual((include / "xy_api.hpp").read_text(encoding="utf-8"), wrapper())

    @unittest.skipUnless(shutil.which("clang++"), "clang++ not on PATH")
    def test_wrapper_compiles_for_a_consumer(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            include = root / "include"
            include.mkdir()
            api = load()
            (include / "xy_api.h").write_text(emit_c.header(api, source_name="x"), encoding="utf-8")
            (include / "xy_api.hpp").write_text(wrapper(), encoding="utf-8")
            driver = include / "xy" / "driver" / "xy_ioctl.h"
            driver.parent.mkdir(parents=True)
            driver.write_text("#define XYD_FEAT_A 1\n", encoding="utf-8")
            tu = root / "consumer.cpp"
            tu.write_text(
                '#include "xy_api.hpp"\n'
                "#include <type_traits>\n\n"
                "static_assert(std::is_move_assignable_v<xy::Port>);\n"
                "static_assert(!std::is_copy_assignable_v<xy::Port>);\n\n"
                "int main() {\n"
                "  xy::Status result = xy::Status::Ok;\n"
                "  auto port = xy::Port::create(0, &result);\n"
                "  if (!port) {\n    return xy::to_string(result)[0];\n  }\n"
                "  char bytes[4] = {};\n"
                "  if (port.send(bytes, sizeof(bytes)) != xy::Status::Ok || port.generation() == xy::FEAT_AB) {\n    return 1;\n  }\n"
                "  port = xy::Port::create(0);\n"
                "  return port && port.pstats().count == 0 ? 0 : 2;\n"
                "}\n",
                encoding="utf-8",
            )
            compiled = subprocess.run(
                ["clang++", "--std=c++20", "-fsyntax-only", "-Wall", "-Wextra", "-Wshadow", "-Werror", f"-I{include}", str(tu)],
                capture_output=True,
                text=True,
            )
            self.assertEqual(compiled.returncode, 0, compiled.stderr)


if __name__ == "__main__":
    unittest.main()
